/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAdminAuditLogsQueryPageDefault = 1;
export const getApiAdminAuditLogsQueryPageSizeDefault = 20;

export const GetApiAdminAuditLogsQueryParams = zod.object({
  "page": zod.number().int().default(getApiAdminAuditLogsQueryPageDefault),
  "pageSize": zod.number().int().default(getApiAdminAuditLogsQueryPageSizeDefault),
  "actionType": zod.string().optional(),
  "adminId": zod.string().optional(),
  "fromDate": zod.string().datetime({"offset":true}).optional(),
  "toDate": zod.string().datetime({"offset":true}).optional()
})

export const GetApiAdminAuditLogsResponse = zod.unknown()

