/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const PostApiPostsBody = zod.object({
  "title": zod.string().nullish(),
  "content": zod.string().nullish(),
  "visibility": zod.string().optional(),
  "media": zod.array(zod.object({
  "postId": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.string().optional(),
  "url": zod.string().optional(),
  "thumbnailUrl": zod.string().optional()
})).optional()
})

export const PostApiPostsResponse = zod.unknown()

export const PutApiPostsBody = zod.object({
  "id": zod.string().nullish(),
  "title": zod.string().nullish(),
  "content": zod.string().nullish(),
  "visibility": zod.string().optional(),
  "media": zod.array(zod.object({
  "id": zod.string().optional(),
  "postId": zod.string().optional(),
  "userId": zod.string().optional(),
  "name": zod.string().optional(),
  "type": zod.string().optional(),
  "url": zod.string().optional(),
  "thumbnailUrl": zod.string().optional(),
  "createdAt": zod.string().datetime({"offset":true}).optional(),
  "updatedAt": zod.string().datetime({"offset":true}).optional()
})).optional()
})

export const PutApiPostsResponse = zod.unknown()

export const PostApiPostsShareBody = zod.object({
  "parentPostId": zod.string(),
  "title": zod.string().nullish(),
  "content": zod.string().nullish(),
  "visibility": zod.string().optional()
})

export const PostApiPostsShareResponse = zod.unknown()

export const getApiPostsMyPostsQueryPageDefault = 1;
export const getApiPostsMyPostsQueryLimitDefault = 20;

export const GetApiPostsMyPostsQueryParams = zod.object({
  "Page": zod.number().int().default(getApiPostsMyPostsQueryPageDefault),
  "Limit": zod.number().int().default(getApiPostsMyPostsQueryLimitDefault)
})

export const GetApiPostsMyPostsResponse = zod.unknown()

export const GetApiPostsUserUserIdParams = zod.object({
  "userId": zod.string()
})

export const getApiPostsUserUserIdQueryPageDefault = 1;
export const getApiPostsUserUserIdQueryLimitDefault = 20;

export const GetApiPostsUserUserIdQueryParams = zod.object({
  "Page": zod.number().int().default(getApiPostsUserUserIdQueryPageDefault),
  "Limit": zod.number().int().default(getApiPostsUserUserIdQueryLimitDefault)
})

export const GetApiPostsUserUserIdResponse = zod.unknown()

export const getApiPostsFeedQueryPageDefault = 1;
export const getApiPostsFeedQueryLimitDefault = 20;

export const GetApiPostsFeedQueryParams = zod.object({
  "Page": zod.number().int().default(getApiPostsFeedQueryPageDefault),
  "Limit": zod.number().int().default(getApiPostsFeedQueryLimitDefault)
})

export const GetApiPostsFeedResponse = zod.unknown()

export const GetApiPostsPostIdParams = zod.object({
  "postId": zod.string()
})

export const GetApiPostsPostIdResponse = zod.unknown()

export const DeleteApiPostsPostIdParams = zod.object({
  "postId": zod.string()
})

export const DeleteApiPostsPostIdResponse = zod.unknown()

