/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminBanUserRequest,
  AdminResetPasswordRequest,
  AdminToggleVerificationRequest,
  AdminUnbanUserRequest,
  AdminUpdateRolesRequest,
  GetApiAdminUsersParams
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiAdminUsers = (
    params?: GetApiAdminUsersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminUsersMutationKey = () => ['getApiAdminUsers'] as const;

export const getGetApiAdminUsersMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError,GetApiAdminUsersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError,GetApiAdminUsersMutationVariables, TContext> => {

const mutationKey = getGetApiAdminUsersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminUsers>>, GetApiAdminUsersMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminUsers(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminUsersMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminUsers>>>

    export type GetApiAdminUsersMutationError = ErrorType<unknown>
    export type GetApiAdminUsersMutationVariables = {params?: GetApiAdminUsersParams}

    export const useGetApiAdminUsers = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminUsers>>, TError,GetApiAdminUsersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminUsers>>,
        TError,
        GetApiAdminUsersMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminUsersMutationOptions(options), queryClient);
    }
    export const postApiAdminUsersUserIdBan = (
    userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users/${userId}/ban`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminBanUserRequest, signal
    },
      options);
    }




export const getPostApiAdminUsersUserIdBanQueryKey = (userId: string,
    adminBanUserRequest?: BodyType<AdminBanUserRequest>,) => {
    return [
    'POST', `/api/admin/users/${userId}/ban`, adminBanUserRequest
    ] as const;
    }


export const getPostApiAdminUsersUserIdBanQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError = ErrorType<unknown>>(userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminUsersUserIdBanQueryKey(userId,adminBanUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>> = ({ signal }) => postApiAdminUsersUserIdBan(userId,adminBanUserRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminUsersUserIdBanQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>>
export type PostApiAdminUsersUserIdBanQueryError = ErrorType<unknown>


export function usePostApiAdminUsersUserIdBan<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError = ErrorType<unknown>>(
 userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdBan<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError = ErrorType<unknown>>(
 userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdBan<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError = ErrorType<unknown>>(
 userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminUsersUserIdBan<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError = ErrorType<unknown>>(
 userId: string,
    adminBanUserRequest: BodyType<AdminBanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdBan>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminUsersUserIdBanQueryOptions(userId,adminBanUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminUsersUserIdUnban = (
    userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users/${userId}/unban`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminUnbanUserRequest, signal
    },
      options);
    }




export const getPostApiAdminUsersUserIdUnbanQueryKey = (userId: string,
    adminUnbanUserRequest?: BodyType<AdminUnbanUserRequest>,) => {
    return [
    'POST', `/api/admin/users/${userId}/unban`, adminUnbanUserRequest
    ] as const;
    }


export const getPostApiAdminUsersUserIdUnbanQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError = ErrorType<unknown>>(userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminUsersUserIdUnbanQueryKey(userId,adminUnbanUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>> = ({ signal }) => postApiAdminUsersUserIdUnban(userId,adminUnbanUserRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminUsersUserIdUnbanQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>>
export type PostApiAdminUsersUserIdUnbanQueryError = ErrorType<unknown>


export function usePostApiAdminUsersUserIdUnban<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdUnban<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdUnban<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminUsersUserIdUnban<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUnbanUserRequest: BodyType<AdminUnbanUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdUnban>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminUsersUserIdUnbanQueryOptions(userId,adminUnbanUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminUsersUserIdRoles = (
    userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users/${userId}/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminUpdateRolesRequest, signal
    },
      options);
    }




export const getPostApiAdminUsersUserIdRolesQueryKey = (userId: string,
    adminUpdateRolesRequest?: BodyType<AdminUpdateRolesRequest>,) => {
    return [
    'POST', `/api/admin/users/${userId}/roles`, adminUpdateRolesRequest
    ] as const;
    }


export const getPostApiAdminUsersUserIdRolesQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError = ErrorType<unknown>>(userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminUsersUserIdRolesQueryKey(userId,adminUpdateRolesRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>> = ({ signal }) => postApiAdminUsersUserIdRoles(userId,adminUpdateRolesRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminUsersUserIdRolesQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>>
export type PostApiAdminUsersUserIdRolesQueryError = ErrorType<unknown>


export function usePostApiAdminUsersUserIdRoles<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdRoles<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdRoles<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminUsersUserIdRoles<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError = ErrorType<unknown>>(
 userId: string,
    adminUpdateRolesRequest: BodyType<AdminUpdateRolesRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdRoles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminUsersUserIdRolesQueryOptions(userId,adminUpdateRolesRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminUsersUserIdVerify = (
    userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users/${userId}/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminToggleVerificationRequest, signal
    },
      options);
    }




export const getPostApiAdminUsersUserIdVerifyQueryKey = (userId: string,
    adminToggleVerificationRequest?: BodyType<AdminToggleVerificationRequest>,) => {
    return [
    'POST', `/api/admin/users/${userId}/verify`, adminToggleVerificationRequest
    ] as const;
    }


export const getPostApiAdminUsersUserIdVerifyQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError = ErrorType<unknown>>(userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminUsersUserIdVerifyQueryKey(userId,adminToggleVerificationRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>> = ({ signal }) => postApiAdminUsersUserIdVerify(userId,adminToggleVerificationRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminUsersUserIdVerifyQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>>
export type PostApiAdminUsersUserIdVerifyQueryError = ErrorType<unknown>


export function usePostApiAdminUsersUserIdVerify<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError = ErrorType<unknown>>(
 userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdVerify<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError = ErrorType<unknown>>(
 userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdVerify<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError = ErrorType<unknown>>(
 userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminUsersUserIdVerify<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError = ErrorType<unknown>>(
 userId: string,
    adminToggleVerificationRequest: BodyType<AdminToggleVerificationRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdVerify>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminUsersUserIdVerifyQueryOptions(userId,adminToggleVerificationRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminUsersUserIdResetPassword = (
    userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/users/${userId}/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminResetPasswordRequest, signal
    },
      options);
    }




export const getPostApiAdminUsersUserIdResetPasswordQueryKey = (userId: string,
    adminResetPasswordRequest?: BodyType<AdminResetPasswordRequest>,) => {
    return [
    'POST', `/api/admin/users/${userId}/reset-password`, adminResetPasswordRequest
    ] as const;
    }


export const getPostApiAdminUsersUserIdResetPasswordQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError = ErrorType<unknown>>(userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminUsersUserIdResetPasswordQueryKey(userId,adminResetPasswordRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>> = ({ signal }) => postApiAdminUsersUserIdResetPassword(userId,adminResetPasswordRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminUsersUserIdResetPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>>
export type PostApiAdminUsersUserIdResetPasswordQueryError = ErrorType<unknown>


export function usePostApiAdminUsersUserIdResetPassword<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError = ErrorType<unknown>>(
 userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdResetPassword<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError = ErrorType<unknown>>(
 userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminUsersUserIdResetPassword<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError = ErrorType<unknown>>(
 userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminUsersUserIdResetPassword<TData = Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError = ErrorType<unknown>>(
 userId: string,
    adminResetPasswordRequest: BodyType<AdminResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminUsersUserIdResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminUsersUserIdResetPasswordQueryOptions(userId,adminResetPasswordRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






