/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCommentRequest,
  CreateReplyCommentRequest,
  GetApiCommentsPostPostIdParams,
  UpdateCommentRequest
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiComments = (
    createCommentRequest: BodyType<CreateCommentRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentRequest, signal
    },
      options);
    }




export const getPostApiCommentsQueryKey = (createCommentRequest?: BodyType<CreateCommentRequest>,) => {
    return [
    'POST', `/api/Comments`, createCommentRequest
    ] as const;
    }


export const getPostApiCommentsQueryOptions = <TData = Awaited<ReturnType<typeof postApiComments>>, TError = ErrorType<unknown>>(createCommentRequest: BodyType<CreateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiCommentsQueryKey(createCommentRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiComments>>> = ({ signal }) => postApiComments(createCommentRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof postApiComments>>>
export type PostApiCommentsQueryError = ErrorType<unknown>


export function usePostApiComments<TData = Awaited<ReturnType<typeof postApiComments>>, TError = ErrorType<unknown>>(
 createCommentRequest: BodyType<CreateCommentRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiComments>>,
          TError,
          Awaited<ReturnType<typeof postApiComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiComments<TData = Awaited<ReturnType<typeof postApiComments>>, TError = ErrorType<unknown>>(
 createCommentRequest: BodyType<CreateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiComments>>,
          TError,
          Awaited<ReturnType<typeof postApiComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiComments<TData = Awaited<ReturnType<typeof postApiComments>>, TError = ErrorType<unknown>>(
 createCommentRequest: BodyType<CreateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiComments<TData = Awaited<ReturnType<typeof postApiComments>>, TError = ErrorType<unknown>>(
 createCommentRequest: BodyType<CreateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiComments>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiCommentsQueryOptions(createCommentRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiCommentsReply = (
    createReplyCommentRequest: BodyType<CreateReplyCommentRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/reply`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createReplyCommentRequest, signal
    },
      options);
    }




export const getPostApiCommentsReplyQueryKey = (createReplyCommentRequest?: BodyType<CreateReplyCommentRequest>,) => {
    return [
    'POST', `/api/Comments/reply`, createReplyCommentRequest
    ] as const;
    }


export const getPostApiCommentsReplyQueryOptions = <TData = Awaited<ReturnType<typeof postApiCommentsReply>>, TError = ErrorType<unknown>>(createReplyCommentRequest: BodyType<CreateReplyCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiCommentsReplyQueryKey(createReplyCommentRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiCommentsReply>>> = ({ signal }) => postApiCommentsReply(createReplyCommentRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiCommentsReplyQueryResult = NonNullable<Awaited<ReturnType<typeof postApiCommentsReply>>>
export type PostApiCommentsReplyQueryError = ErrorType<unknown>


export function usePostApiCommentsReply<TData = Awaited<ReturnType<typeof postApiCommentsReply>>, TError = ErrorType<unknown>>(
 createReplyCommentRequest: BodyType<CreateReplyCommentRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCommentsReply>>,
          TError,
          Awaited<ReturnType<typeof postApiCommentsReply>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiCommentsReply<TData = Awaited<ReturnType<typeof postApiCommentsReply>>, TError = ErrorType<unknown>>(
 createReplyCommentRequest: BodyType<CreateReplyCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiCommentsReply>>,
          TError,
          Awaited<ReturnType<typeof postApiCommentsReply>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiCommentsReply<TData = Awaited<ReturnType<typeof postApiCommentsReply>>, TError = ErrorType<unknown>>(
 createReplyCommentRequest: BodyType<CreateReplyCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiCommentsReply<TData = Awaited<ReturnType<typeof postApiCommentsReply>>, TError = ErrorType<unknown>>(
 createReplyCommentRequest: BodyType<CreateReplyCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiCommentsReply>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiCommentsReplyQueryOptions(createReplyCommentRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiCommentsCommentId = (
    commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/${commentId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCommentRequest, signal
    },
      options);
    }




export const getPutApiCommentsCommentIdQueryKey = (commentId: string,
    updateCommentRequest?: BodyType<UpdateCommentRequest>,) => {
    return [
    'PUT', `/api/Comments/${commentId}`, updateCommentRequest
    ] as const;
    }


export const getPutApiCommentsCommentIdQueryOptions = <TData = Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError = ErrorType<unknown>>(commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPutApiCommentsCommentIdQueryKey(commentId,updateCommentRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiCommentsCommentId>>> = ({ signal }) => putApiCommentsCommentId(commentId,updateCommentRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: commentId !== null && commentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PutApiCommentsCommentIdQueryResult = NonNullable<Awaited<ReturnType<typeof putApiCommentsCommentId>>>
export type PutApiCommentsCommentIdQueryError = ErrorType<unknown>


export function usePutApiCommentsCommentId<TData = Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiCommentsCommentId>>,
          TError,
          Awaited<ReturnType<typeof putApiCommentsCommentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiCommentsCommentId<TData = Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiCommentsCommentId>>,
          TError,
          Awaited<ReturnType<typeof putApiCommentsCommentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiCommentsCommentId<TData = Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePutApiCommentsCommentId<TData = Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string,
    updateCommentRequest: BodyType<UpdateCommentRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutApiCommentsCommentIdQueryOptions(commentId,updateCommentRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiCommentsCommentId = (
    commentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/${commentId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiCommentsCommentIdQueryKey = (commentId: string,) => {
    return [
    'DELETE', `/api/Comments/${commentId}`
    ] as const;
    }


export const getDeleteApiCommentsCommentIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError = ErrorType<unknown>>(commentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiCommentsCommentIdQueryKey(commentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>> = ({ signal }) => deleteApiCommentsCommentId(commentId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: commentId !== null && commentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiCommentsCommentIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>>
export type DeleteApiCommentsCommentIdQueryError = ErrorType<unknown>


export function useDeleteApiCommentsCommentId<TData = Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCommentsCommentId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCommentsCommentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiCommentsCommentId<TData = Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiCommentsCommentId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiCommentsCommentId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiCommentsCommentId<TData = Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiCommentsCommentId<TData = Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError = ErrorType<unknown>>(
 commentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiCommentsCommentId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiCommentsCommentIdQueryOptions(commentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiCommentsCommentId = (
    commentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/${commentId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiCommentsCommentIdMutationKey = () => ['getApiCommentsCommentId'] as const;

export const getGetApiCommentsCommentIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsCommentId>>, TError,GetApiCommentsCommentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsCommentId>>, TError,GetApiCommentsCommentIdMutationVariables, TContext> => {

const mutationKey = getGetApiCommentsCommentIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiCommentsCommentId>>, GetApiCommentsCommentIdMutationVariables> = (props) => {
          const {commentId} = props ?? {};

          return  getApiCommentsCommentId(commentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiCommentsCommentIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiCommentsCommentId>>>

    export type GetApiCommentsCommentIdMutationError = ErrorType<unknown>
    export type GetApiCommentsCommentIdMutationVariables = {commentId: string}

    export const useGetApiCommentsCommentId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsCommentId>>, TError,GetApiCommentsCommentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiCommentsCommentId>>,
        TError,
        GetApiCommentsCommentIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiCommentsCommentIdMutationOptions(options), queryClient);
    }
    export const getApiCommentsPostPostId = (
    postId: string,
    params?: GetApiCommentsPostPostIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/post/${postId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiCommentsPostPostIdMutationKey = () => ['getApiCommentsPostPostId'] as const;

export const getGetApiCommentsPostPostIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsPostPostId>>, TError,GetApiCommentsPostPostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsPostPostId>>, TError,GetApiCommentsPostPostIdMutationVariables, TContext> => {

const mutationKey = getGetApiCommentsPostPostIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiCommentsPostPostId>>, GetApiCommentsPostPostIdMutationVariables> = (props) => {
          const {postId,params} = props ?? {};

          return  getApiCommentsPostPostId(postId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiCommentsPostPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiCommentsPostPostId>>>

    export type GetApiCommentsPostPostIdMutationError = ErrorType<unknown>
    export type GetApiCommentsPostPostIdMutationVariables = {postId: string;params?: GetApiCommentsPostPostIdParams}

    export const useGetApiCommentsPostPostId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsPostPostId>>, TError,GetApiCommentsPostPostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiCommentsPostPostId>>,
        TError,
        GetApiCommentsPostPostIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiCommentsPostPostIdMutationOptions(options), queryClient);
    }
    export const getApiCommentsRepliesParentId = (
    parentId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Comments/replies/${parentId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiCommentsRepliesParentIdMutationKey = () => ['getApiCommentsRepliesParentId'] as const;

export const getGetApiCommentsRepliesParentIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>, TError,GetApiCommentsRepliesParentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>, TError,GetApiCommentsRepliesParentIdMutationVariables, TContext> => {

const mutationKey = getGetApiCommentsRepliesParentIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>, GetApiCommentsRepliesParentIdMutationVariables> = (props) => {
          const {parentId} = props ?? {};

          return  getApiCommentsRepliesParentId(parentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiCommentsRepliesParentIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>>

    export type GetApiCommentsRepliesParentIdMutationError = ErrorType<unknown>
    export type GetApiCommentsRepliesParentIdMutationVariables = {parentId: string}

    export const useGetApiCommentsRepliesParentId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>, TError,GetApiCommentsRepliesParentIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiCommentsRepliesParentId>>,
        TError,
        GetApiCommentsRepliesParentIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiCommentsRepliesParentIdMutationOptions(options), queryClient);
    }
