/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GetApiAdminAnalyticsContentVelocityParams,
  GetApiAdminAnalyticsRequestStreamParams,
  GetApiAdminAnalyticsSafetyMetricsParams,
  GetApiAdminAnalyticsUserGrowthParams
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getApiAdminAnalyticsOverview = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/overview`, method: 'GET', signal
    },
      options);
    }




export const getGetApiAdminAnalyticsOverviewMutationKey = () => ['getApiAdminAnalyticsOverview'] as const;

export const getGetApiAdminAnalyticsOverviewMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>, TError,void, TContext> => {

const mutationKey = getGetApiAdminAnalyticsOverviewMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>, void> = () => {


          return  getApiAdminAnalyticsOverview(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsOverviewMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>>

    export type GetApiAdminAnalyticsOverviewMutationError = ErrorType<unknown>


    export const useGetApiAdminAnalyticsOverview = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsOverview>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsOverviewMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsDiagnostics = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/diagnostics`, method: 'GET', signal
    },
      options);
    }




export const getGetApiAdminAnalyticsDiagnosticsMutationKey = () => ['getApiAdminAnalyticsDiagnostics'] as const;

export const getGetApiAdminAnalyticsDiagnosticsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>, TError,void, TContext> => {

const mutationKey = getGetApiAdminAnalyticsDiagnosticsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>, void> = () => {


          return  getApiAdminAnalyticsDiagnostics(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsDiagnosticsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>>

    export type GetApiAdminAnalyticsDiagnosticsMutationError = ErrorType<unknown>


    export const useGetApiAdminAnalyticsDiagnostics = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsDiagnostics>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsDiagnosticsMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsKpiSummary = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/kpi-summary`, method: 'GET', signal
    },
      options);
    }




export const getGetApiAdminAnalyticsKpiSummaryMutationKey = () => ['getApiAdminAnalyticsKpiSummary'] as const;

export const getGetApiAdminAnalyticsKpiSummaryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>, TError,void, TContext> => {

const mutationKey = getGetApiAdminAnalyticsKpiSummaryMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>, void> = () => {


          return  getApiAdminAnalyticsKpiSummary(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsKpiSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>>

    export type GetApiAdminAnalyticsKpiSummaryMutationError = ErrorType<unknown>


    export const useGetApiAdminAnalyticsKpiSummary = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsKpiSummary>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsKpiSummaryMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsUserGrowth = (
    params?: GetApiAdminAnalyticsUserGrowthParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/user-growth`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminAnalyticsUserGrowthMutationKey = () => ['getApiAdminAnalyticsUserGrowth'] as const;

export const getGetApiAdminAnalyticsUserGrowthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>, TError,GetApiAdminAnalyticsUserGrowthMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>, TError,GetApiAdminAnalyticsUserGrowthMutationVariables, TContext> => {

const mutationKey = getGetApiAdminAnalyticsUserGrowthMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>, GetApiAdminAnalyticsUserGrowthMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminAnalyticsUserGrowth(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsUserGrowthMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>>

    export type GetApiAdminAnalyticsUserGrowthMutationError = ErrorType<unknown>
    export type GetApiAdminAnalyticsUserGrowthMutationVariables = {params?: GetApiAdminAnalyticsUserGrowthParams}

    export const useGetApiAdminAnalyticsUserGrowth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>, TError,GetApiAdminAnalyticsUserGrowthMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsUserGrowth>>,
        TError,
        GetApiAdminAnalyticsUserGrowthMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsUserGrowthMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsContentVelocity = (
    params?: GetApiAdminAnalyticsContentVelocityParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/content-velocity`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminAnalyticsContentVelocityMutationKey = () => ['getApiAdminAnalyticsContentVelocity'] as const;

export const getGetApiAdminAnalyticsContentVelocityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>, TError,GetApiAdminAnalyticsContentVelocityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>, TError,GetApiAdminAnalyticsContentVelocityMutationVariables, TContext> => {

const mutationKey = getGetApiAdminAnalyticsContentVelocityMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>, GetApiAdminAnalyticsContentVelocityMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminAnalyticsContentVelocity(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsContentVelocityMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>>

    export type GetApiAdminAnalyticsContentVelocityMutationError = ErrorType<unknown>
    export type GetApiAdminAnalyticsContentVelocityMutationVariables = {params?: GetApiAdminAnalyticsContentVelocityParams}

    export const useGetApiAdminAnalyticsContentVelocity = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>, TError,GetApiAdminAnalyticsContentVelocityMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsContentVelocity>>,
        TError,
        GetApiAdminAnalyticsContentVelocityMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsContentVelocityMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsApiHealth = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/api-health`, method: 'GET', signal
    },
      options);
    }




export const getGetApiAdminAnalyticsApiHealthMutationKey = () => ['getApiAdminAnalyticsApiHealth'] as const;

export const getGetApiAdminAnalyticsApiHealthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>, TError,void, TContext> => {

const mutationKey = getGetApiAdminAnalyticsApiHealthMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>, void> = () => {


          return  getApiAdminAnalyticsApiHealth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsApiHealthMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>>

    export type GetApiAdminAnalyticsApiHealthMutationError = ErrorType<unknown>


    export const useGetApiAdminAnalyticsApiHealth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsApiHealth>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsApiHealthMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsSafetyMetrics = (
    params?: GetApiAdminAnalyticsSafetyMetricsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/safety-metrics`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminAnalyticsSafetyMetricsMutationKey = () => ['getApiAdminAnalyticsSafetyMetrics'] as const;

export const getGetApiAdminAnalyticsSafetyMetricsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>, TError,GetApiAdminAnalyticsSafetyMetricsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>, TError,GetApiAdminAnalyticsSafetyMetricsMutationVariables, TContext> => {

const mutationKey = getGetApiAdminAnalyticsSafetyMetricsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>, GetApiAdminAnalyticsSafetyMetricsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminAnalyticsSafetyMetrics(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsSafetyMetricsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>>

    export type GetApiAdminAnalyticsSafetyMetricsMutationError = ErrorType<unknown>
    export type GetApiAdminAnalyticsSafetyMetricsMutationVariables = {params?: GetApiAdminAnalyticsSafetyMetricsParams}

    export const useGetApiAdminAnalyticsSafetyMetrics = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>, TError,GetApiAdminAnalyticsSafetyMetricsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsSafetyMetrics>>,
        TError,
        GetApiAdminAnalyticsSafetyMetricsMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsSafetyMetricsMutationOptions(options), queryClient);
    }
    export const getApiAdminAnalyticsRequestStream = (
    params?: GetApiAdminAnalyticsRequestStreamParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/analytics/request-stream`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminAnalyticsRequestStreamMutationKey = () => ['getApiAdminAnalyticsRequestStream'] as const;

export const getGetApiAdminAnalyticsRequestStreamMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>, TError,GetApiAdminAnalyticsRequestStreamMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>, TError,GetApiAdminAnalyticsRequestStreamMutationVariables, TContext> => {

const mutationKey = getGetApiAdminAnalyticsRequestStreamMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>, GetApiAdminAnalyticsRequestStreamMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminAnalyticsRequestStream(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAnalyticsRequestStreamMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>>

    export type GetApiAdminAnalyticsRequestStreamMutationError = ErrorType<unknown>
    export type GetApiAdminAnalyticsRequestStreamMutationVariables = {params?: GetApiAdminAnalyticsRequestStreamParams}

    export const useGetApiAdminAnalyticsRequestStream = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>, TError,GetApiAdminAnalyticsRequestStreamMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAnalyticsRequestStream>>,
        TError,
        GetApiAdminAnalyticsRequestStreamMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminAnalyticsRequestStreamMutationOptions(options), queryClient);
    }
