/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
export const PostApiNotificationsBody = zod.object({
    "userId": zod.string().optional(),
    "recipientId": zod.string().optional(),
    "type": zod.string().optional(),
    "message": zod.string().optional(),
    "postId": zod.string().nullish(),
    "commentId": zod.string().nullish(),
    "followerId": zod.string().nullish(),
    "likeId": zod.string().nullish(),
    "imageUrl": zod.string().nullish(),
    "lastActorName": zod.string().nullish()
});
export const PostApiNotificationsResponse = zod.unknown();
export const GetApiNotificationsIdParams = zod.object({
    "id": zod.string()
});
export const GetApiNotificationsIdResponse = zod.unknown();
export const PutApiNotificationsIdParams = zod.object({
    "id": zod.string()
});
export const PutApiNotificationsIdBody = zod.object({
    "id": zod.string().optional(),
    "userId": zod.string().optional(),
    "recipientId": zod.string().optional(),
    "type": zod.string().optional(),
    "message": zod.string().optional(),
    "postId": zod.string().nullish(),
    "commentId": zod.string().nullish(),
    "followerId": zod.string().nullish(),
    "likeId": zod.string().nullish(),
    "imageUrl": zod.string().nullish(),
    "lastActorName": zod.string().nullish()
});
export const PutApiNotificationsIdResponse = zod.unknown();
export const DeleteApiNotificationsIdParams = zod.object({
    "id": zod.string()
});
export const DeleteApiNotificationsIdResponse = zod.unknown();
export const GetApiNotificationsUserUserIdParams = zod.object({
    "userId": zod.string()
});
export const getApiNotificationsUserUserIdQueryPageDefault = 1;
export const getApiNotificationsUserUserIdQueryLimitDefault = 20;
export const GetApiNotificationsUserUserIdQueryParams = zod.object({
    "page": zod.number().int().default(getApiNotificationsUserUserIdQueryPageDefault),
    "limit": zod.number().int().default(getApiNotificationsUserUserIdQueryLimitDefault)
});
export const GetApiNotificationsUserUserIdResponse = zod.unknown();
export const GetApiNotificationsUserUserIdUnreadParams = zod.object({
    "userId": zod.string()
});
export const getApiNotificationsUserUserIdUnreadQueryPageDefault = 1;
export const getApiNotificationsUserUserIdUnreadQueryLimitDefault = 20;
export const GetApiNotificationsUserUserIdUnreadQueryParams = zod.object({
    "page": zod.number().int().default(getApiNotificationsUserUserIdUnreadQueryPageDefault),
    "limit": zod.number().int().default(getApiNotificationsUserUserIdUnreadQueryLimitDefault)
});
export const GetApiNotificationsUserUserIdUnreadResponse = zod.unknown();
export const PostApiNotificationsIdMarkReadParams = zod.object({
    "id": zod.string()
});
export const PostApiNotificationsIdMarkReadResponse = zod.unknown();
export const PostApiNotificationsUserUserIdMarkAllReadParams = zod.object({
    "userId": zod.string()
});
export const PostApiNotificationsUserUserIdMarkAllReadResponse = zod.unknown();
export const DeleteApiNotificationsUserUserIdAllParams = zod.object({
    "userId": zod.string()
});
export const DeleteApiNotificationsUserUserIdAllResponse = zod.unknown();
export const getApiNotificationsInboxQueryUnreadOnlyDefault = false;
export const getApiNotificationsInboxQueryPageDefault = 1;
export const getApiNotificationsInboxQueryLimitDefault = 20;
export const GetApiNotificationsInboxQueryParams = zod.object({
    "type": zod.string().optional(),
    "unreadOnly": zod.boolean().default(getApiNotificationsInboxQueryUnreadOnlyDefault),
    "page": zod.number().int().default(getApiNotificationsInboxQueryPageDefault),
    "limit": zod.number().int().default(getApiNotificationsInboxQueryLimitDefault)
});
export const GetApiNotificationsInboxResponse = zod.unknown();
export const GetApiNotificationsUnreadCountResponse = zod.unknown();
export const GetApiNotificationsPreferencesResponse = zod.unknown();
export const PutApiNotificationsPreferencesBody = zod.object({
    "userId": zod.string().optional(),
    "likeEnabled": zod.boolean().optional(),
    "commentEnabled": zod.boolean().optional(),
    "replyEnabled": zod.boolean().optional(),
    "followEnabled": zod.boolean().optional(),
    "followRequestEnabled": zod.boolean().optional(),
    "shareEnabled": zod.boolean().optional(),
    "mentionEnabled": zod.boolean().optional(),
    "quietStartHourUtc": zod.number().int().nullish(),
    "quietEndHourUtc": zod.number().int().nullish(),
    "digestEnabled": zod.boolean().optional()
});
export const PutApiNotificationsPreferencesResponse = zod.unknown();
