/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAdminModerationFeedQueryPageDefault = 1;
export const getApiAdminModerationFeedQueryPageSizeDefault = 20;

export const GetApiAdminModerationFeedQueryParams = zod.object({
  "page": zod.number().int().default(getApiAdminModerationFeedQueryPageDefault),
  "pageSize": zod.number().int().default(getApiAdminModerationFeedQueryPageSizeDefault)
})

export const GetApiAdminModerationFeedResponse = zod.unknown()

export const PostApiAdminModerationPostsPostIdHideParams = zod.object({
  "postId": zod.string()
})

export const PostApiAdminModerationPostsPostIdHideBody = zod.object({
  "reason": zod.string().optional()
})

export const PostApiAdminModerationPostsPostIdHideResponse = zod.unknown()

export const PostApiAdminModerationPostsPostIdRestoreParams = zod.object({
  "postId": zod.string()
})

export const PostApiAdminModerationPostsPostIdRestoreBody = zod.object({
  "reason": zod.string().optional()
})

export const PostApiAdminModerationPostsPostIdRestoreResponse = zod.unknown()

export const PostApiAdminModerationCommentsCommentIdHideParams = zod.object({
  "commentId": zod.string()
})

export const PostApiAdminModerationCommentsCommentIdHideBody = zod.object({
  "reason": zod.string().optional()
})

export const PostApiAdminModerationCommentsCommentIdHideResponse = zod.unknown()

export const PostApiAdminModerationCommentsCommentIdRestoreParams = zod.object({
  "commentId": zod.string()
})

export const PostApiAdminModerationCommentsCommentIdRestoreBody = zod.object({
  "reason": zod.string().optional()
})

export const PostApiAdminModerationCommentsCommentIdRestoreResponse = zod.unknown()

export const PostApiAdminModerationPostsPostIdVisibilityParams = zod.object({
  "postId": zod.string()
})

export const PostApiAdminModerationPostsPostIdVisibilityBody = zod.object({
  "visibility": zod.string().optional(),
  "reason": zod.string().optional()
})

export const PostApiAdminModerationPostsPostIdVisibilityResponse = zod.unknown()

export const DeleteApiAdminModerationPostsPostIdParams = zod.object({
  "postId": zod.string()
})

export const DeleteApiAdminModerationPostsPostIdQueryParams = zod.object({
  "reason": zod.string().optional()
})

export const DeleteApiAdminModerationPostsPostIdResponse = zod.unknown()

export const getApiAdminModerationReportsQueryPageDefault = 1;
export const getApiAdminModerationReportsQueryPageSizeDefault = 20;

export const GetApiAdminModerationReportsQueryParams = zod.object({
  "status": zod.string().optional(),
  "page": zod.number().int().default(getApiAdminModerationReportsQueryPageDefault),
  "pageSize": zod.number().int().default(getApiAdminModerationReportsQueryPageSizeDefault)
})

export const GetApiAdminModerationReportsResponse = zod.unknown()

export const GetApiAdminModerationReportsReportIdParams = zod.object({
  "reportId": zod.string()
})

export const GetApiAdminModerationReportsReportIdResponse = zod.unknown()

export const PostApiAdminModerationReportsReportIdResolveParams = zod.object({
  "reportId": zod.string()
})

export const PostApiAdminModerationReportsReportIdResolveBody = zod.object({
  "action": zod.string().optional(),
  "note": zod.string().nullish()
})

export const PostApiAdminModerationReportsReportIdResolveResponse = zod.unknown()

