/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const PostApiLikeBody = zod.object({
  "postId": zod.string().optional()
})

export const PostApiLikeResponse = zod.unknown()

export const GetApiLikePostIdParams = zod.object({
  "postId": zod.string()
})

export const getApiLikePostIdQueryPageDefault = 1;
export const getApiLikePostIdQueryLimitDefault = 20;

export const GetApiLikePostIdQueryParams = zod.object({
  "page": zod.number().int().default(getApiLikePostIdQueryPageDefault),
  "limit": zod.number().int().default(getApiLikePostIdQueryLimitDefault)
})

export const GetApiLikePostIdResponse = zod.unknown()

