/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BlockUserRequest,
  GetApiBlockUserBlockedUsersParams,
  GetApiBlockUserIsBlockedParams
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiBlockUserBlockedUsers = (
    params?: GetApiBlockUserBlockedUsersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/BlockUser/blocked-users`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiBlockUserBlockedUsersMutationKey = () => ['getApiBlockUserBlockedUsers'] as const;

export const getGetApiBlockUserBlockedUsersMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>, TError,GetApiBlockUserBlockedUsersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>, TError,GetApiBlockUserBlockedUsersMutationVariables, TContext> => {

const mutationKey = getGetApiBlockUserBlockedUsersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>, GetApiBlockUserBlockedUsersMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiBlockUserBlockedUsers(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiBlockUserBlockedUsersMutationResult = NonNullable<Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>>

    export type GetApiBlockUserBlockedUsersMutationError = ErrorType<unknown>
    export type GetApiBlockUserBlockedUsersMutationVariables = {params?: GetApiBlockUserBlockedUsersParams}

    export const useGetApiBlockUserBlockedUsers = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>, TError,GetApiBlockUserBlockedUsersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiBlockUserBlockedUsers>>,
        TError,
        GetApiBlockUserBlockedUsersMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiBlockUserBlockedUsersMutationOptions(options), queryClient);
    }
    export const getApiBlockUserIsBlocked = (
    params?: GetApiBlockUserIsBlockedParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/BlockUser/is-blocked`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiBlockUserIsBlockedMutationKey = () => ['getApiBlockUserIsBlocked'] as const;

export const getGetApiBlockUserIsBlockedMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>, TError,GetApiBlockUserIsBlockedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>, TError,GetApiBlockUserIsBlockedMutationVariables, TContext> => {

const mutationKey = getGetApiBlockUserIsBlockedMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>, GetApiBlockUserIsBlockedMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiBlockUserIsBlocked(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiBlockUserIsBlockedMutationResult = NonNullable<Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>>

    export type GetApiBlockUserIsBlockedMutationError = ErrorType<unknown>
    export type GetApiBlockUserIsBlockedMutationVariables = {params?: GetApiBlockUserIsBlockedParams}

    export const useGetApiBlockUserIsBlocked = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>, TError,GetApiBlockUserIsBlockedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiBlockUserIsBlocked>>,
        TError,
        GetApiBlockUserIsBlockedMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiBlockUserIsBlockedMutationOptions(options), queryClient);
    }
    export const postApiBlockUserBlock = (
    blockUserRequest: BodyType<BlockUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/BlockUser/block`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: blockUserRequest, signal
    },
      options);
    }




export const getPostApiBlockUserBlockQueryKey = (blockUserRequest?: BodyType<BlockUserRequest>,) => {
    return [
    'POST', `/api/BlockUser/block`, blockUserRequest
    ] as const;
    }


export const getPostApiBlockUserBlockQueryOptions = <TData = Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError = ErrorType<unknown>>(blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiBlockUserBlockQueryKey(blockUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiBlockUserBlock>>> = ({ signal }) => postApiBlockUserBlock(blockUserRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiBlockUserBlockQueryResult = NonNullable<Awaited<ReturnType<typeof postApiBlockUserBlock>>>
export type PostApiBlockUserBlockQueryError = ErrorType<unknown>


export function usePostApiBlockUserBlock<TData = Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBlockUserBlock>>,
          TError,
          Awaited<ReturnType<typeof postApiBlockUserBlock>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiBlockUserBlock<TData = Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBlockUserBlock>>,
          TError,
          Awaited<ReturnType<typeof postApiBlockUserBlock>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiBlockUserBlock<TData = Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiBlockUserBlock<TData = Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserBlock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiBlockUserBlockQueryOptions(blockUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiBlockUserUnblock = (
    blockUserRequest: BodyType<BlockUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/BlockUser/unblock`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: blockUserRequest, signal
    },
      options);
    }




export const getPostApiBlockUserUnblockQueryKey = (blockUserRequest?: BodyType<BlockUserRequest>,) => {
    return [
    'POST', `/api/BlockUser/unblock`, blockUserRequest
    ] as const;
    }


export const getPostApiBlockUserUnblockQueryOptions = <TData = Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError = ErrorType<unknown>>(blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiBlockUserUnblockQueryKey(blockUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiBlockUserUnblock>>> = ({ signal }) => postApiBlockUserUnblock(blockUserRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiBlockUserUnblockQueryResult = NonNullable<Awaited<ReturnType<typeof postApiBlockUserUnblock>>>
export type PostApiBlockUserUnblockQueryError = ErrorType<unknown>


export function usePostApiBlockUserUnblock<TData = Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBlockUserUnblock>>,
          TError,
          Awaited<ReturnType<typeof postApiBlockUserUnblock>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiBlockUserUnblock<TData = Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiBlockUserUnblock>>,
          TError,
          Awaited<ReturnType<typeof postApiBlockUserUnblock>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiBlockUserUnblock<TData = Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiBlockUserUnblock<TData = Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError = ErrorType<unknown>>(
 blockUserRequest: BodyType<BlockUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiBlockUserUnblock>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiBlockUserUnblockQueryOptions(blockUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






