/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface AdminBanUserRequest {
  reason?: string;
  /** @nullable */
  durationDays?: number | null;
}
