/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface CreateNotificationDto {
  userId?: string;
  recipientId?: string;
  type?: string;
  message?: string;
  /** @nullable */
  postId?: string | null;
  /** @nullable */
  commentId?: string | null;
  /** @nullable */
  followerId?: string | null;
  /** @nullable */
  likeId?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  lastActorName?: string | null;
}
