/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import type { CreateMediaRequest } from './createMediaRequest';

export interface CreatePostRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  visibility?: string;
  media?: CreateMediaRequest[];
}
