/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  userName: string;
  userGender: string;
  email: string;
  password: string;
  birthDate: string;
  bio: string;
}
