/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface CreateReplyCommentRequest {
  postId?: string;
  content?: string;
  parentId?: string;
}
