/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface CreateMediaRequest {
  postId?: string;
  name?: string;
  type?: string;
  url?: string;
  thumbnailUrl?: string;
}
