/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export type GetApiAdminAuditLogsParams = {
page?: number;
pageSize?: number;
actionType?: string;
adminId?: string;
fromDate?: string;
toDate?: string;
};
