/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export type GetApiAdminModerationReportsParams = {
status?: string;
page?: number;
pageSize?: number;
};
