/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export type GetApiNotificationsInboxParams = {
type?: string;
unreadOnly?: boolean;
page?: number;
limit?: number;
};
