/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface MediaDto {
  id?: string;
  postId?: string;
  userId?: string;
  name?: string;
  type?: string;
  url?: string;
  thumbnailUrl?: string;
  createdAt?: string;
  updatedAt?: string;
}
