/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface NotificationPreferenceDto {
  userId?: string;
  likeEnabled?: boolean;
  commentEnabled?: boolean;
  replyEnabled?: boolean;
  followEnabled?: boolean;
  followRequestEnabled?: boolean;
  shareEnabled?: boolean;
  mentionEnabled?: boolean;
  /** @nullable */
  quietStartHourUtc?: number | null;
  /** @nullable */
  quietEndHourUtc?: number | null;
  digestEnabled?: boolean;
}
