/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface ResetPasswordRequest {
  email: string;
  token: string;
  /**
     * @minLength 8
     * @maxLength 100
     * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$
     */
  password: string;
  confirmPassword: string;
}
