/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface ResolveReportRequest {
  action?: string;
  /** @nullable */
  note?: string | null;
}
