/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface SharePostRequest {
  parentPostId: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  visibility?: string;
}
