/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */

export interface UpdateUserDto {
  id?: string;
  firstName?: string;
  lastName?: string;
  userName?: string;
  birthDate?: string;
  bio?: string;
  profileImageUrl?: string;
  isPrivate?: boolean;
}
