/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import type { MediaDto } from './mediaDto';

export interface UpdatePostRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  content?: string | null;
  visibility?: string;
  media?: MediaDto[];
}
