/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
export const getApiBlockUserBlockedUsersQueryPageDefault = 1;
export const getApiBlockUserBlockedUsersQueryLimitDefault = 20;
export const GetApiBlockUserBlockedUsersQueryParams = zod.object({
    "page": zod.number().int().default(getApiBlockUserBlockedUsersQueryPageDefault),
    "limit": zod.number().int().default(getApiBlockUserBlockedUsersQueryLimitDefault)
});
export const GetApiBlockUserBlockedUsersResponse = zod.unknown();
export const GetApiBlockUserIsBlockedQueryParams = zod.object({
    "blockedUserId": zod.string().optional()
});
export const GetApiBlockUserIsBlockedResponse = zod.unknown();
export const PostApiBlockUserBlockBody = zod.object({
    "blockedUserId": zod.string()
});
export const PostApiBlockUserBlockResponse = zod.unknown();
export const PostApiBlockUserUnblockBody = zod.object({
    "blockedUserId": zod.string()
});
export const PostApiBlockUserUnblockResponse = zod.unknown();
