/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiAdminAnalyticsOverviewResponse = zod.unknown()

export const GetApiAdminAnalyticsDiagnosticsResponse = zod.unknown()

export const GetApiAdminAnalyticsKpiSummaryResponse = zod.unknown()

export const getApiAdminAnalyticsUserGrowthQueryRangeDefault = `30d`;

export const GetApiAdminAnalyticsUserGrowthQueryParams = zod.object({
  "range": zod.string().default(getApiAdminAnalyticsUserGrowthQueryRangeDefault)
})

export const GetApiAdminAnalyticsUserGrowthResponse = zod.unknown()

export const getApiAdminAnalyticsContentVelocityQueryDaysDefault = 30;

export const GetApiAdminAnalyticsContentVelocityQueryParams = zod.object({
  "days": zod.number().int().default(getApiAdminAnalyticsContentVelocityQueryDaysDefault)
})

export const GetApiAdminAnalyticsContentVelocityResponse = zod.unknown()

export const GetApiAdminAnalyticsApiHealthResponse = zod.unknown()

export const getApiAdminAnalyticsSafetyMetricsQueryDaysDefault = 30;

export const GetApiAdminAnalyticsSafetyMetricsQueryParams = zod.object({
  "days": zod.number().int().default(getApiAdminAnalyticsSafetyMetricsQueryDaysDefault)
})

export const GetApiAdminAnalyticsSafetyMetricsResponse = zod.unknown()

export const getApiAdminAnalyticsRequestStreamQueryTakeDefault = 50;

export const GetApiAdminAnalyticsRequestStreamQueryParams = zod.object({
  "take": zod.number().int().default(getApiAdminAnalyticsRequestStreamQueryTakeDefault)
})

export const GetApiAdminAnalyticsRequestStreamResponse = zod.unknown()

