/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAdminUsersQueryPageDefault = 1;
export const getApiAdminUsersQueryPageSizeDefault = 10;

export const GetApiAdminUsersQueryParams = zod.object({
  "page": zod.number().int().default(getApiAdminUsersQueryPageDefault),
  "pageSize": zod.number().int().default(getApiAdminUsersQueryPageSizeDefault),
  "q": zod.string().optional()
})

export const GetApiAdminUsersResponse = zod.unknown()

export const PostApiAdminUsersUserIdBanParams = zod.object({
  "userId": zod.string()
})

export const PostApiAdminUsersUserIdBanBody = zod.object({
  "reason": zod.string().optional(),
  "durationDays": zod.number().int().nullish()
})

export const PostApiAdminUsersUserIdBanResponse = zod.unknown()

export const PostApiAdminUsersUserIdUnbanParams = zod.object({
  "userId": zod.string()
})

export const PostApiAdminUsersUserIdUnbanBody = zod.object({
  "reason": zod.string().optional()
})

export const PostApiAdminUsersUserIdUnbanResponse = zod.unknown()

export const PostApiAdminUsersUserIdRolesParams = zod.object({
  "userId": zod.string()
})

export const PostApiAdminUsersUserIdRolesBody = zod.object({
  "roles": zod.array(zod.string()).optional(),
  "reason": zod.string().optional()
})

export const PostApiAdminUsersUserIdRolesResponse = zod.unknown()

export const PostApiAdminUsersUserIdVerifyParams = zod.object({
  "userId": zod.string()
})

export const PostApiAdminUsersUserIdVerifyBody = zod.object({
  "isVerified": zod.boolean().optional(),
  "reason": zod.string().optional()
})

export const PostApiAdminUsersUserIdVerifyResponse = zod.unknown()

export const PostApiAdminUsersUserIdResetPasswordParams = zod.object({
  "userId": zod.string()
})

export const PostApiAdminUsersUserIdResetPasswordBody = zod.object({
  "newPassword": zod.string().nullish(),
  "reason": zod.string().optional()
})

export const PostApiAdminUsersUserIdResetPasswordResponse = zod.unknown()

