/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FollowRequest,
  GetApiFollowFollowersParams,
  GetApiFollowFollowingParams,
  GetApiFollowPendingFollowRequestsParams
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiFollowFollow = (
    followRequest: BodyType<FollowRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/follow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: followRequest, signal
    },
      options);
    }




export const getPostApiFollowFollowQueryKey = (followRequest?: BodyType<FollowRequest>,) => {
    return [
    'POST', `/api/Follow/follow`, followRequest
    ] as const;
    }


export const getPostApiFollowFollowQueryOptions = <TData = Awaited<ReturnType<typeof postApiFollowFollow>>, TError = ErrorType<unknown>>(followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiFollowFollowQueryKey(followRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiFollowFollow>>> = ({ signal }) => postApiFollowFollow(followRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiFollowFollowQueryResult = NonNullable<Awaited<ReturnType<typeof postApiFollowFollow>>>
export type PostApiFollowFollowQueryError = ErrorType<unknown>


export function usePostApiFollowFollow<TData = Awaited<ReturnType<typeof postApiFollowFollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowFollow>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowFollow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowFollow<TData = Awaited<ReturnType<typeof postApiFollowFollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowFollow>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowFollow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowFollow<TData = Awaited<ReturnType<typeof postApiFollowFollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiFollowFollow<TData = Awaited<ReturnType<typeof postApiFollowFollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowFollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiFollowFollowQueryOptions(followRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiFollowUnfollow = (
    followRequest: BodyType<FollowRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/unfollow`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: followRequest, signal
    },
      options);
    }




export const getPostApiFollowUnfollowQueryKey = (followRequest?: BodyType<FollowRequest>,) => {
    return [
    'POST', `/api/Follow/unfollow`, followRequest
    ] as const;
    }


export const getPostApiFollowUnfollowQueryOptions = <TData = Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError = ErrorType<unknown>>(followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiFollowUnfollowQueryKey(followRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiFollowUnfollow>>> = ({ signal }) => postApiFollowUnfollow(followRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiFollowUnfollowQueryResult = NonNullable<Awaited<ReturnType<typeof postApiFollowUnfollow>>>
export type PostApiFollowUnfollowQueryError = ErrorType<unknown>


export function usePostApiFollowUnfollow<TData = Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowUnfollow>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowUnfollow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowUnfollow<TData = Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowUnfollow>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowUnfollow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowUnfollow<TData = Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiFollowUnfollow<TData = Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowUnfollow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiFollowUnfollowQueryOptions(followRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiFollowAcceptFollowRequest = (
    followRequest: BodyType<FollowRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/accept-follow-request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: followRequest, signal
    },
      options);
    }




export const getPostApiFollowAcceptFollowRequestQueryKey = (followRequest?: BodyType<FollowRequest>,) => {
    return [
    'POST', `/api/Follow/accept-follow-request`, followRequest
    ] as const;
    }


export const getPostApiFollowAcceptFollowRequestQueryOptions = <TData = Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError = ErrorType<unknown>>(followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiFollowAcceptFollowRequestQueryKey(followRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>> = ({ signal }) => postApiFollowAcceptFollowRequest(followRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiFollowAcceptFollowRequestQueryResult = NonNullable<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>>
export type PostApiFollowAcceptFollowRequestQueryError = ErrorType<unknown>


export function usePostApiFollowAcceptFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowAcceptFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowAcceptFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiFollowAcceptFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowAcceptFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiFollowAcceptFollowRequestQueryOptions(followRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiFollowRejectFollowRequest = (
    followRequest: BodyType<FollowRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/reject-follow-request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: followRequest, signal
    },
      options);
    }




export const getPostApiFollowRejectFollowRequestQueryKey = (followRequest?: BodyType<FollowRequest>,) => {
    return [
    'POST', `/api/Follow/reject-follow-request`, followRequest
    ] as const;
    }


export const getPostApiFollowRejectFollowRequestQueryOptions = <TData = Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError = ErrorType<unknown>>(followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiFollowRejectFollowRequestQueryKey(followRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>> = ({ signal }) => postApiFollowRejectFollowRequest(followRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiFollowRejectFollowRequestQueryResult = NonNullable<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>>
export type PostApiFollowRejectFollowRequestQueryError = ErrorType<unknown>


export function usePostApiFollowRejectFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowRejectFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>,
          TError,
          Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiFollowRejectFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiFollowRejectFollowRequest<TData = Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError = ErrorType<unknown>>(
 followRequest: BodyType<FollowRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiFollowRejectFollowRequest>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiFollowRejectFollowRequestQueryOptions(followRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiFollowFollowers = (
    params?: GetApiFollowFollowersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/followers`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiFollowFollowersMutationKey = () => ['getApiFollowFollowers'] as const;

export const getGetApiFollowFollowersMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowers>>, TError,GetApiFollowFollowersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowers>>, TError,GetApiFollowFollowersMutationVariables, TContext> => {

const mutationKey = getGetApiFollowFollowersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiFollowFollowers>>, GetApiFollowFollowersMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiFollowFollowers(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiFollowFollowersMutationResult = NonNullable<Awaited<ReturnType<typeof getApiFollowFollowers>>>

    export type GetApiFollowFollowersMutationError = ErrorType<unknown>
    export type GetApiFollowFollowersMutationVariables = {params?: GetApiFollowFollowersParams}

    export const useGetApiFollowFollowers = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowers>>, TError,GetApiFollowFollowersMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiFollowFollowers>>,
        TError,
        GetApiFollowFollowersMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiFollowFollowersMutationOptions(options), queryClient);
    }
    export const getApiFollowFollowing = (
    params?: GetApiFollowFollowingParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/following`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiFollowFollowingMutationKey = () => ['getApiFollowFollowing'] as const;

export const getGetApiFollowFollowingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowing>>, TError,GetApiFollowFollowingMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowing>>, TError,GetApiFollowFollowingMutationVariables, TContext> => {

const mutationKey = getGetApiFollowFollowingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiFollowFollowing>>, GetApiFollowFollowingMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiFollowFollowing(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiFollowFollowingMutationResult = NonNullable<Awaited<ReturnType<typeof getApiFollowFollowing>>>

    export type GetApiFollowFollowingMutationError = ErrorType<unknown>
    export type GetApiFollowFollowingMutationVariables = {params?: GetApiFollowFollowingParams}

    export const useGetApiFollowFollowing = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowFollowing>>, TError,GetApiFollowFollowingMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiFollowFollowing>>,
        TError,
        GetApiFollowFollowingMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiFollowFollowingMutationOptions(options), queryClient);
    }
    export const getApiFollowPendingFollowRequests = (
    params?: GetApiFollowPendingFollowRequestsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Follow/pending-follow-requests`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiFollowPendingFollowRequestsMutationKey = () => ['getApiFollowPendingFollowRequests'] as const;

export const getGetApiFollowPendingFollowRequestsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>, TError,GetApiFollowPendingFollowRequestsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>, TError,GetApiFollowPendingFollowRequestsMutationVariables, TContext> => {

const mutationKey = getGetApiFollowPendingFollowRequestsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>, GetApiFollowPendingFollowRequestsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiFollowPendingFollowRequests(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiFollowPendingFollowRequestsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>>

    export type GetApiFollowPendingFollowRequestsMutationError = ErrorType<unknown>
    export type GetApiFollowPendingFollowRequestsMutationVariables = {params?: GetApiFollowPendingFollowRequestsParams}

    export const useGetApiFollowPendingFollowRequests = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>, TError,GetApiFollowPendingFollowRequestsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiFollowPendingFollowRequests>>,
        TError,
        GetApiFollowPendingFollowRequestsMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiFollowPendingFollowRequestsMutationOptions(options), queryClient);
    }
