/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiLikePostIdParams,
  LikeRequest
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiLike = (
    likeRequest: BodyType<LikeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Like`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: likeRequest, signal
    },
      options);
    }




export const getPostApiLikeQueryKey = (likeRequest?: BodyType<LikeRequest>,) => {
    return [
    'POST', `/api/Like`, likeRequest
    ] as const;
    }


export const getPostApiLikeQueryOptions = <TData = Awaited<ReturnType<typeof postApiLike>>, TError = ErrorType<unknown>>(likeRequest: BodyType<LikeRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiLikeQueryKey(likeRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiLike>>> = ({ signal }) => postApiLike(likeRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiLikeQueryResult = NonNullable<Awaited<ReturnType<typeof postApiLike>>>
export type PostApiLikeQueryError = ErrorType<unknown>


export function usePostApiLike<TData = Awaited<ReturnType<typeof postApiLike>>, TError = ErrorType<unknown>>(
 likeRequest: BodyType<LikeRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiLike>>,
          TError,
          Awaited<ReturnType<typeof postApiLike>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiLike<TData = Awaited<ReturnType<typeof postApiLike>>, TError = ErrorType<unknown>>(
 likeRequest: BodyType<LikeRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiLike>>,
          TError,
          Awaited<ReturnType<typeof postApiLike>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiLike<TData = Awaited<ReturnType<typeof postApiLike>>, TError = ErrorType<unknown>>(
 likeRequest: BodyType<LikeRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiLike<TData = Awaited<ReturnType<typeof postApiLike>>, TError = ErrorType<unknown>>(
 likeRequest: BodyType<LikeRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiLike>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiLikeQueryOptions(likeRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiLikePostId = (
    postId: string,
    params?: GetApiLikePostIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Like/${postId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiLikePostIdMutationKey = () => ['getApiLikePostId'] as const;

export const getGetApiLikePostIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiLikePostId>>, TError,GetApiLikePostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiLikePostId>>, TError,GetApiLikePostIdMutationVariables, TContext> => {

const mutationKey = getGetApiLikePostIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiLikePostId>>, GetApiLikePostIdMutationVariables> = (props) => {
          const {postId,params} = props ?? {};

          return  getApiLikePostId(postId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiLikePostIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiLikePostId>>>

    export type GetApiLikePostIdMutationError = ErrorType<unknown>
    export type GetApiLikePostIdMutationVariables = {postId: string;params?: GetApiLikePostIdParams}

    export const useGetApiLikePostId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiLikePostId>>, TError,GetApiLikePostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiLikePostId>>,
        TError,
        GetApiLikePostIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiLikePostIdMutationOptions(options), queryClient);
    }
