/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePostRequest,
  GetApiPostsFeedParams,
  GetApiPostsMyPostsParams,
  GetApiPostsReportsMineParams,
  GetApiPostsUserUserIdParams,
  ReportPostRequest,
  SharePostRequest,
  UpdatePostRequest
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiPosts = (
    createPostRequest: BodyType<CreatePostRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostRequest, signal
    },
      options);
    }




export const getPostApiPostsQueryKey = (createPostRequest?: BodyType<CreatePostRequest>,) => {
    return [
    'POST', `/api/Posts`, createPostRequest
    ] as const;
    }


export const getPostApiPostsQueryOptions = <TData = Awaited<ReturnType<typeof postApiPosts>>, TError = ErrorType<unknown>>(createPostRequest: BodyType<CreatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiPostsQueryKey(createPostRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiPosts>>> = ({ signal }) => postApiPosts(createPostRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiPostsQueryResult = NonNullable<Awaited<ReturnType<typeof postApiPosts>>>
export type PostApiPostsQueryError = ErrorType<unknown>


export function usePostApiPosts<TData = Awaited<ReturnType<typeof postApiPosts>>, TError = ErrorType<unknown>>(
 createPostRequest: BodyType<CreatePostRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPosts>>,
          TError,
          Awaited<ReturnType<typeof postApiPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPosts<TData = Awaited<ReturnType<typeof postApiPosts>>, TError = ErrorType<unknown>>(
 createPostRequest: BodyType<CreatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPosts>>,
          TError,
          Awaited<ReturnType<typeof postApiPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPosts<TData = Awaited<ReturnType<typeof postApiPosts>>, TError = ErrorType<unknown>>(
 createPostRequest: BodyType<CreatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiPosts<TData = Awaited<ReturnType<typeof postApiPosts>>, TError = ErrorType<unknown>>(
 createPostRequest: BodyType<CreatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiPostsQueryOptions(createPostRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiPosts = (
    updatePostRequest: BodyType<UpdatePostRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePostRequest, signal
    },
      options);
    }




export const getPutApiPostsQueryKey = (updatePostRequest?: BodyType<UpdatePostRequest>,) => {
    return [
    'PUT', `/api/Posts`, updatePostRequest
    ] as const;
    }


export const getPutApiPostsQueryOptions = <TData = Awaited<ReturnType<typeof putApiPosts>>, TError = ErrorType<unknown>>(updatePostRequest: BodyType<UpdatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPutApiPostsQueryKey(updatePostRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiPosts>>> = ({ signal }) => putApiPosts(updatePostRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PutApiPostsQueryResult = NonNullable<Awaited<ReturnType<typeof putApiPosts>>>
export type PutApiPostsQueryError = ErrorType<unknown>


export function usePutApiPosts<TData = Awaited<ReturnType<typeof putApiPosts>>, TError = ErrorType<unknown>>(
 updatePostRequest: BodyType<UpdatePostRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiPosts>>,
          TError,
          Awaited<ReturnType<typeof putApiPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiPosts<TData = Awaited<ReturnType<typeof putApiPosts>>, TError = ErrorType<unknown>>(
 updatePostRequest: BodyType<UpdatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiPosts>>,
          TError,
          Awaited<ReturnType<typeof putApiPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiPosts<TData = Awaited<ReturnType<typeof putApiPosts>>, TError = ErrorType<unknown>>(
 updatePostRequest: BodyType<UpdatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePutApiPosts<TData = Awaited<ReturnType<typeof putApiPosts>>, TError = ErrorType<unknown>>(
 updatePostRequest: BodyType<UpdatePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiPosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutApiPostsQueryOptions(updatePostRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiPostsShare = (
    sharePostRequest: BodyType<SharePostRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/share`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sharePostRequest, signal
    },
      options);
    }




export const getPostApiPostsShareQueryKey = (sharePostRequest?: BodyType<SharePostRequest>,) => {
    return [
    'POST', `/api/Posts/share`, sharePostRequest
    ] as const;
    }


export const getPostApiPostsShareQueryOptions = <TData = Awaited<ReturnType<typeof postApiPostsShare>>, TError = ErrorType<unknown>>(sharePostRequest: BodyType<SharePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiPostsShareQueryKey(sharePostRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiPostsShare>>> = ({ signal }) => postApiPostsShare(sharePostRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiPostsShareQueryResult = NonNullable<Awaited<ReturnType<typeof postApiPostsShare>>>
export type PostApiPostsShareQueryError = ErrorType<unknown>


export function usePostApiPostsShare<TData = Awaited<ReturnType<typeof postApiPostsShare>>, TError = ErrorType<unknown>>(
 sharePostRequest: BodyType<SharePostRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPostsShare>>,
          TError,
          Awaited<ReturnType<typeof postApiPostsShare>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPostsShare<TData = Awaited<ReturnType<typeof postApiPostsShare>>, TError = ErrorType<unknown>>(
 sharePostRequest: BodyType<SharePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPostsShare>>,
          TError,
          Awaited<ReturnType<typeof postApiPostsShare>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPostsShare<TData = Awaited<ReturnType<typeof postApiPostsShare>>, TError = ErrorType<unknown>>(
 sharePostRequest: BodyType<SharePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiPostsShare<TData = Awaited<ReturnType<typeof postApiPostsShare>>, TError = ErrorType<unknown>>(
 sharePostRequest: BodyType<SharePostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsShare>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiPostsShareQueryOptions(sharePostRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiPostsMyPosts = (
    params?: GetApiPostsMyPostsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/my-posts`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiPostsMyPostsMutationKey = () => ['getApiPostsMyPosts'] as const;

export const getGetApiPostsMyPostsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsMyPosts>>, TError,GetApiPostsMyPostsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiPostsMyPosts>>, TError,GetApiPostsMyPostsMutationVariables, TContext> => {

const mutationKey = getGetApiPostsMyPostsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiPostsMyPosts>>, GetApiPostsMyPostsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiPostsMyPosts(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiPostsMyPostsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiPostsMyPosts>>>

    export type GetApiPostsMyPostsMutationError = ErrorType<unknown>
    export type GetApiPostsMyPostsMutationVariables = {params?: GetApiPostsMyPostsParams}

    export const useGetApiPostsMyPosts = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsMyPosts>>, TError,GetApiPostsMyPostsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiPostsMyPosts>>,
        TError,
        GetApiPostsMyPostsMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiPostsMyPostsMutationOptions(options), queryClient);
    }
    export const getApiPostsUserUserId = (
    userId: string,
    params?: GetApiPostsUserUserIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/user/${userId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiPostsUserUserIdMutationKey = () => ['getApiPostsUserUserId'] as const;

export const getGetApiPostsUserUserIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsUserUserId>>, TError,GetApiPostsUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiPostsUserUserId>>, TError,GetApiPostsUserUserIdMutationVariables, TContext> => {

const mutationKey = getGetApiPostsUserUserIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiPostsUserUserId>>, GetApiPostsUserUserIdMutationVariables> = (props) => {
          const {userId,params} = props ?? {};

          return  getApiPostsUserUserId(userId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiPostsUserUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiPostsUserUserId>>>

    export type GetApiPostsUserUserIdMutationError = ErrorType<unknown>
    export type GetApiPostsUserUserIdMutationVariables = {userId: string;params?: GetApiPostsUserUserIdParams}

    export const useGetApiPostsUserUserId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsUserUserId>>, TError,GetApiPostsUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiPostsUserUserId>>,
        TError,
        GetApiPostsUserUserIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiPostsUserUserIdMutationOptions(options), queryClient);
    }
    export const getApiPostsFeed = (
    params?: GetApiPostsFeedParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/feed`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiPostsFeedMutationKey = () => ['getApiPostsFeed'] as const;

export const getGetApiPostsFeedMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsFeed>>, TError,GetApiPostsFeedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiPostsFeed>>, TError,GetApiPostsFeedMutationVariables, TContext> => {

const mutationKey = getGetApiPostsFeedMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiPostsFeed>>, GetApiPostsFeedMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiPostsFeed(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiPostsFeedMutationResult = NonNullable<Awaited<ReturnType<typeof getApiPostsFeed>>>

    export type GetApiPostsFeedMutationError = ErrorType<unknown>
    export type GetApiPostsFeedMutationVariables = {params?: GetApiPostsFeedParams}

    export const useGetApiPostsFeed = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsFeed>>, TError,GetApiPostsFeedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiPostsFeed>>,
        TError,
        GetApiPostsFeedMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiPostsFeedMutationOptions(options), queryClient);
    }
    export const getApiPostsPostId = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/${postId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiPostsPostIdMutationKey = () => ['getApiPostsPostId'] as const;

export const getGetApiPostsPostIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsPostId>>, TError,GetApiPostsPostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiPostsPostId>>, TError,GetApiPostsPostIdMutationVariables, TContext> => {

const mutationKey = getGetApiPostsPostIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiPostsPostId>>, GetApiPostsPostIdMutationVariables> = (props) => {
          const {postId} = props ?? {};

          return  getApiPostsPostId(postId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiPostsPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiPostsPostId>>>

    export type GetApiPostsPostIdMutationError = ErrorType<unknown>
    export type GetApiPostsPostIdMutationVariables = {postId: string}

    export const useGetApiPostsPostId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsPostId>>, TError,GetApiPostsPostIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiPostsPostId>>,
        TError,
        GetApiPostsPostIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiPostsPostIdMutationOptions(options), queryClient);
    }
    export const deleteApiPostsPostId = (
    postId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/${postId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiPostsPostIdQueryKey = (postId: string,) => {
    return [
    'DELETE', `/api/Posts/${postId}`
    ] as const;
    }


export const getDeleteApiPostsPostIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError = ErrorType<unknown>>(postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiPostsPostIdQueryKey(postId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiPostsPostId>>> = ({ signal }) => deleteApiPostsPostId(postId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiPostsPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiPostsPostId>>>
export type DeleteApiPostsPostIdQueryError = ErrorType<unknown>


export function useDeleteApiPostsPostId<TData = Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiPostsPostId<TData = Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiPostsPostId<TData = Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiPostsPostId<TData = Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiPostsPostIdQueryOptions(postId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiPostsReportsMine = (
    params?: GetApiPostsReportsMineParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/reports/mine`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiPostsReportsMineMutationKey = () => ['getApiPostsReportsMine'] as const;

export const getGetApiPostsReportsMineMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsReportsMine>>, TError,GetApiPostsReportsMineMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiPostsReportsMine>>, TError,GetApiPostsReportsMineMutationVariables, TContext> => {

const mutationKey = getGetApiPostsReportsMineMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiPostsReportsMine>>, GetApiPostsReportsMineMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiPostsReportsMine(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiPostsReportsMineMutationResult = NonNullable<Awaited<ReturnType<typeof getApiPostsReportsMine>>>

    export type GetApiPostsReportsMineMutationError = ErrorType<unknown>
    export type GetApiPostsReportsMineMutationVariables = {params?: GetApiPostsReportsMineParams}

    export const useGetApiPostsReportsMine = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiPostsReportsMine>>, TError,GetApiPostsReportsMineMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiPostsReportsMine>>,
        TError,
        GetApiPostsReportsMineMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiPostsReportsMineMutationOptions(options), queryClient);
    }
    export const postApiPostsPostIdReport = (
    postId: string,
    reportPostRequest: BodyType<ReportPostRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/${postId}/report`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reportPostRequest, signal
    },
      options);
    }




export const getPostApiPostsPostIdReportQueryKey = (postId: string,
    reportPostRequest?: BodyType<ReportPostRequest>,) => {
    return [
    'POST', `/api/Posts/${postId}/report`, reportPostRequest
    ] as const;
    }


export const getPostApiPostsPostIdReportQueryOptions = <TData = Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError = ErrorType<unknown>>(postId: string,
    reportPostRequest: BodyType<ReportPostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiPostsPostIdReportQueryKey(postId,reportPostRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiPostsPostIdReport>>> = ({ signal }) => postApiPostsPostIdReport(postId,reportPostRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiPostsPostIdReportQueryResult = NonNullable<Awaited<ReturnType<typeof postApiPostsPostIdReport>>>
export type PostApiPostsPostIdReportQueryError = ErrorType<unknown>


export function usePostApiPostsPostIdReport<TData = Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError = ErrorType<unknown>>(
 postId: string,
    reportPostRequest: BodyType<ReportPostRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPostsPostIdReport>>,
          TError,
          Awaited<ReturnType<typeof postApiPostsPostIdReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPostsPostIdReport<TData = Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError = ErrorType<unknown>>(
 postId: string,
    reportPostRequest: BodyType<ReportPostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiPostsPostIdReport>>,
          TError,
          Awaited<ReturnType<typeof postApiPostsPostIdReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiPostsPostIdReport<TData = Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError = ErrorType<unknown>>(
 postId: string,
    reportPostRequest: BodyType<ReportPostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiPostsPostIdReport<TData = Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError = ErrorType<unknown>>(
 postId: string,
    reportPostRequest: BodyType<ReportPostRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiPostsPostIdReport>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiPostsPostIdReportQueryOptions(postId,reportPostRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiPostsReportsReportId = (
    reportId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Posts/reports/${reportId}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiPostsReportsReportIdQueryKey = (reportId: string,) => {
    return [
    'DELETE', `/api/Posts/reports/${reportId}`
    ] as const;
    }


export const getDeleteApiPostsReportsReportIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError = ErrorType<unknown>>(reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiPostsReportsReportIdQueryKey(reportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>> = ({ signal }) => deleteApiPostsReportsReportId(reportId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiPostsReportsReportIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>>
export type DeleteApiPostsReportsReportIdQueryError = ErrorType<unknown>


export function useDeleteApiPostsReportsReportId<TData = Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError = ErrorType<unknown>>(
 reportId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiPostsReportsReportId<TData = Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError = ErrorType<unknown>>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiPostsReportsReportId<TData = Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError = ErrorType<unknown>>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiPostsReportsReportId<TData = Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError = ErrorType<unknown>>(
 reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiPostsReportsReportId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiPostsReportsReportIdQueryOptions(reportId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






