/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminModerationActionRequest,
  AdminUpdateVisibilityRequest,
  DeleteApiAdminModerationPostsPostIdParams,
  GetApiAdminModerationFeedParams,
  GetApiAdminModerationReportsParams,
  ResolveReportRequest
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiAdminModerationFeed = (
    params?: GetApiAdminModerationFeedParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/feed`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminModerationFeedMutationKey = () => ['getApiAdminModerationFeed'] as const;

export const getGetApiAdminModerationFeedMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationFeed>>, TError,GetApiAdminModerationFeedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationFeed>>, TError,GetApiAdminModerationFeedMutationVariables, TContext> => {

const mutationKey = getGetApiAdminModerationFeedMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminModerationFeed>>, GetApiAdminModerationFeedMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminModerationFeed(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminModerationFeedMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminModerationFeed>>>

    export type GetApiAdminModerationFeedMutationError = ErrorType<unknown>
    export type GetApiAdminModerationFeedMutationVariables = {params?: GetApiAdminModerationFeedParams}

    export const useGetApiAdminModerationFeed = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationFeed>>, TError,GetApiAdminModerationFeedMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminModerationFeed>>,
        TError,
        GetApiAdminModerationFeedMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminModerationFeedMutationOptions(options), queryClient);
    }
    export const postApiAdminModerationPostsPostIdHide = (
    postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/posts/${postId}/hide`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminModerationActionRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationPostsPostIdHideQueryKey = (postId: string,
    adminModerationActionRequest?: BodyType<AdminModerationActionRequest>,) => {
    return [
    'POST', `/api/admin/moderation/posts/${postId}/hide`, adminModerationActionRequest
    ] as const;
    }


export const getPostApiAdminModerationPostsPostIdHideQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError = ErrorType<unknown>>(postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationPostsPostIdHideQueryKey(postId,adminModerationActionRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>> = ({ signal }) => postApiAdminModerationPostsPostIdHide(postId,adminModerationActionRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationPostsPostIdHideQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>>
export type PostApiAdminModerationPostsPostIdHideQueryError = ErrorType<unknown>


export function usePostApiAdminModerationPostsPostIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationPostsPostIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationPostsPostIdHideQueryOptions(postId,adminModerationActionRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminModerationPostsPostIdRestore = (
    postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/posts/${postId}/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminModerationActionRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationPostsPostIdRestoreQueryKey = (postId: string,
    adminModerationActionRequest?: BodyType<AdminModerationActionRequest>,) => {
    return [
    'POST', `/api/admin/moderation/posts/${postId}/restore`, adminModerationActionRequest
    ] as const;
    }


export const getPostApiAdminModerationPostsPostIdRestoreQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError = ErrorType<unknown>>(postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationPostsPostIdRestoreQueryKey(postId,adminModerationActionRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>> = ({ signal }) => postApiAdminModerationPostsPostIdRestore(postId,adminModerationActionRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationPostsPostIdRestoreQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>>
export type PostApiAdminModerationPostsPostIdRestoreQueryError = ErrorType<unknown>


export function usePostApiAdminModerationPostsPostIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationPostsPostIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError = ErrorType<unknown>>(
 postId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationPostsPostIdRestoreQueryOptions(postId,adminModerationActionRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminModerationCommentsCommentIdHide = (
    commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/comments/${commentId}/hide`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminModerationActionRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationCommentsCommentIdHideQueryKey = (commentId: string,
    adminModerationActionRequest?: BodyType<AdminModerationActionRequest>,) => {
    return [
    'POST', `/api/admin/moderation/comments/${commentId}/hide`, adminModerationActionRequest
    ] as const;
    }


export const getPostApiAdminModerationCommentsCommentIdHideQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError = ErrorType<unknown>>(commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationCommentsCommentIdHideQueryKey(commentId,adminModerationActionRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>> = ({ signal }) => postApiAdminModerationCommentsCommentIdHide(commentId,adminModerationActionRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: commentId !== null && commentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationCommentsCommentIdHideQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>>
export type PostApiAdminModerationCommentsCommentIdHideQueryError = ErrorType<unknown>


export function usePostApiAdminModerationCommentsCommentIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationCommentsCommentIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationCommentsCommentIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationCommentsCommentIdHide<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdHide>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationCommentsCommentIdHideQueryOptions(commentId,adminModerationActionRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminModerationCommentsCommentIdRestore = (
    commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/comments/${commentId}/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminModerationActionRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationCommentsCommentIdRestoreQueryKey = (commentId: string,
    adminModerationActionRequest?: BodyType<AdminModerationActionRequest>,) => {
    return [
    'POST', `/api/admin/moderation/comments/${commentId}/restore`, adminModerationActionRequest
    ] as const;
    }


export const getPostApiAdminModerationCommentsCommentIdRestoreQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError = ErrorType<unknown>>(commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationCommentsCommentIdRestoreQueryKey(commentId,adminModerationActionRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>> = ({ signal }) => postApiAdminModerationCommentsCommentIdRestore(commentId,adminModerationActionRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: commentId !== null && commentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationCommentsCommentIdRestoreQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>>
export type PostApiAdminModerationCommentsCommentIdRestoreQueryError = ErrorType<unknown>


export function usePostApiAdminModerationCommentsCommentIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationCommentsCommentIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationCommentsCommentIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationCommentsCommentIdRestore<TData = Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError = ErrorType<unknown>>(
 commentId: string,
    adminModerationActionRequest: BodyType<AdminModerationActionRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationCommentsCommentIdRestore>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationCommentsCommentIdRestoreQueryOptions(commentId,adminModerationActionRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiAdminModerationPostsPostIdVisibility = (
    postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/posts/${postId}/visibility`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminUpdateVisibilityRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationPostsPostIdVisibilityQueryKey = (postId: string,
    adminUpdateVisibilityRequest?: BodyType<AdminUpdateVisibilityRequest>,) => {
    return [
    'POST', `/api/admin/moderation/posts/${postId}/visibility`, adminUpdateVisibilityRequest
    ] as const;
    }


export const getPostApiAdminModerationPostsPostIdVisibilityQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError = ErrorType<unknown>>(postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationPostsPostIdVisibilityQueryKey(postId,adminUpdateVisibilityRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>> = ({ signal }) => postApiAdminModerationPostsPostIdVisibility(postId,adminUpdateVisibilityRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationPostsPostIdVisibilityQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>>
export type PostApiAdminModerationPostsPostIdVisibilityQueryError = ErrorType<unknown>


export function usePostApiAdminModerationPostsPostIdVisibility<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError = ErrorType<unknown>>(
 postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdVisibility<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError = ErrorType<unknown>>(
 postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationPostsPostIdVisibility<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError = ErrorType<unknown>>(
 postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationPostsPostIdVisibility<TData = Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError = ErrorType<unknown>>(
 postId: string,
    adminUpdateVisibilityRequest: BodyType<AdminUpdateVisibilityRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationPostsPostIdVisibility>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationPostsPostIdVisibilityQueryOptions(postId,adminUpdateVisibilityRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiAdminModerationPostsPostId = (
    postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/posts/${postId}`, method: 'DELETE',
        params, signal
    },
      options);
    }




export const getDeleteApiAdminModerationPostsPostIdQueryKey = (postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams,) => {
    return [
    'DELETE', `/api/admin/moderation/posts/${postId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getDeleteApiAdminModerationPostsPostIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError = ErrorType<unknown>>(postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiAdminModerationPostsPostIdQueryKey(postId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>> = ({ signal }) => deleteApiAdminModerationPostsPostId(postId,params, requestOptions, signal);





   return  { queryKey, queryFn, enabled: postId !== null && postId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiAdminModerationPostsPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>>
export type DeleteApiAdminModerationPostsPostIdQueryError = ErrorType<unknown>


export function useDeleteApiAdminModerationPostsPostId<TData = Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params: undefined |  DeleteApiAdminModerationPostsPostIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiAdminModerationPostsPostId<TData = Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiAdminModerationPostsPostId<TData = Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiAdminModerationPostsPostId<TData = Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError = ErrorType<unknown>>(
 postId: string,
    params?: DeleteApiAdminModerationPostsPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiAdminModerationPostsPostId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiAdminModerationPostsPostIdQueryOptions(postId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiAdminModerationReports = (
    params?: GetApiAdminModerationReportsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/reports`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminModerationReportsMutationKey = () => ['getApiAdminModerationReports'] as const;

export const getGetApiAdminModerationReportsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReports>>, TError,GetApiAdminModerationReportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReports>>, TError,GetApiAdminModerationReportsMutationVariables, TContext> => {

const mutationKey = getGetApiAdminModerationReportsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminModerationReports>>, GetApiAdminModerationReportsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminModerationReports(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminModerationReportsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminModerationReports>>>

    export type GetApiAdminModerationReportsMutationError = ErrorType<unknown>
    export type GetApiAdminModerationReportsMutationVariables = {params?: GetApiAdminModerationReportsParams}

    export const useGetApiAdminModerationReports = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReports>>, TError,GetApiAdminModerationReportsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminModerationReports>>,
        TError,
        GetApiAdminModerationReportsMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminModerationReportsMutationOptions(options), queryClient);
    }
    export const getApiAdminModerationReportsReportId = (
    reportId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/reports/${reportId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiAdminModerationReportsReportIdMutationKey = () => ['getApiAdminModerationReportsReportId'] as const;

export const getGetApiAdminModerationReportsReportIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>, TError,GetApiAdminModerationReportsReportIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>, TError,GetApiAdminModerationReportsReportIdMutationVariables, TContext> => {

const mutationKey = getGetApiAdminModerationReportsReportIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>, GetApiAdminModerationReportsReportIdMutationVariables> = (props) => {
          const {reportId} = props ?? {};

          return  getApiAdminModerationReportsReportId(reportId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminModerationReportsReportIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>>

    export type GetApiAdminModerationReportsReportIdMutationError = ErrorType<unknown>
    export type GetApiAdminModerationReportsReportIdMutationVariables = {reportId: string}

    export const useGetApiAdminModerationReportsReportId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>, TError,GetApiAdminModerationReportsReportIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminModerationReportsReportId>>,
        TError,
        GetApiAdminModerationReportsReportIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminModerationReportsReportIdMutationOptions(options), queryClient);
    }
    export const postApiAdminModerationReportsReportIdResolve = (
    reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/moderation/reports/${reportId}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveReportRequest, signal
    },
      options);
    }




export const getPostApiAdminModerationReportsReportIdResolveQueryKey = (reportId: string,
    resolveReportRequest?: BodyType<ResolveReportRequest>,) => {
    return [
    'POST', `/api/admin/moderation/reports/${reportId}/resolve`, resolveReportRequest
    ] as const;
    }


export const getPostApiAdminModerationReportsReportIdResolveQueryOptions = <TData = Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError = ErrorType<unknown>>(reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiAdminModerationReportsReportIdResolveQueryKey(reportId,resolveReportRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>> = ({ signal }) => postApiAdminModerationReportsReportIdResolve(reportId,resolveReportRequest, requestOptions, signal);





   return  { queryKey, queryFn, enabled: reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiAdminModerationReportsReportIdResolveQueryResult = NonNullable<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>>
export type PostApiAdminModerationReportsReportIdResolveQueryError = ErrorType<unknown>


export function usePostApiAdminModerationReportsReportIdResolve<TData = Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError = ErrorType<unknown>>(
 reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationReportsReportIdResolve<TData = Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError = ErrorType<unknown>>(
 reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>,
          TError,
          Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiAdminModerationReportsReportIdResolve<TData = Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError = ErrorType<unknown>>(
 reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiAdminModerationReportsReportIdResolve<TData = Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError = ErrorType<unknown>>(
 reportId: string,
    resolveReportRequest: BodyType<ResolveReportRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiAdminModerationReportsReportIdResolve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiAdminModerationReportsReportIdResolveQueryOptions(reportId,resolveReportRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






