/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangePasswordRequest,
  CreateUserRequest,
  ForgetPasswordRequest,
  GetApiUserSearchParams,
  RefreshTokenRequest,
  ResetPasswordRequest,
  SignIn,
  UpdateUserDto
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiUserRegister = (
    createUserRequest: BodyType<CreateUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest, signal
    },
      options);
    }




export const getPostApiUserRegisterQueryKey = (createUserRequest?: BodyType<CreateUserRequest>,) => {
    return [
    'POST', `/api/User/register`, createUserRequest
    ] as const;
    }


export const getPostApiUserRegisterQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserRegister>>, TError = ErrorType<unknown>>(createUserRequest: BodyType<CreateUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserRegisterQueryKey(createUserRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserRegister>>> = ({ signal }) => postApiUserRegister(createUserRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserRegister>>>
export type PostApiUserRegisterQueryError = ErrorType<unknown>


export function usePostApiUserRegister<TData = Awaited<ReturnType<typeof postApiUserRegister>>, TError = ErrorType<unknown>>(
 createUserRequest: BodyType<CreateUserRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserRegister>>,
          TError,
          Awaited<ReturnType<typeof postApiUserRegister>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserRegister<TData = Awaited<ReturnType<typeof postApiUserRegister>>, TError = ErrorType<unknown>>(
 createUserRequest: BodyType<CreateUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserRegister>>,
          TError,
          Awaited<ReturnType<typeof postApiUserRegister>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserRegister<TData = Awaited<ReturnType<typeof postApiUserRegister>>, TError = ErrorType<unknown>>(
 createUserRequest: BodyType<CreateUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserRegister<TData = Awaited<ReturnType<typeof postApiUserRegister>>, TError = ErrorType<unknown>>(
 createUserRequest: BodyType<CreateUserRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRegister>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserRegisterQueryOptions(createUserRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserSignIn = (
    signIn: BodyType<SignIn>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/sign-in`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signIn, signal
    },
      options);
    }




export const getPostApiUserSignInQueryKey = (signIn?: BodyType<SignIn>,) => {
    return [
    'POST', `/api/User/sign-in`, signIn
    ] as const;
    }


export const getPostApiUserSignInQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserSignIn>>, TError = ErrorType<unknown>>(signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserSignInQueryKey(signIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserSignIn>>> = ({ signal }) => postApiUserSignIn(signIn, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserSignInQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserSignIn>>>
export type PostApiUserSignInQueryError = ErrorType<unknown>


export function usePostApiUserSignIn<TData = Awaited<ReturnType<typeof postApiUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserSignIn>>,
          TError,
          Awaited<ReturnType<typeof postApiUserSignIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserSignIn<TData = Awaited<ReturnType<typeof postApiUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserSignIn>>,
          TError,
          Awaited<ReturnType<typeof postApiUserSignIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserSignIn<TData = Awaited<ReturnType<typeof postApiUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserSignIn<TData = Awaited<ReturnType<typeof postApiUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserSignInQueryOptions(signIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserRefreshToken = (
    refreshTokenRequest: BodyType<RefreshTokenRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
      options);
    }




export const getPostApiUserRefreshTokenQueryKey = (refreshTokenRequest?: BodyType<RefreshTokenRequest>,) => {
    return [
    'POST', `/api/User/refresh-token`, refreshTokenRequest
    ] as const;
    }


export const getPostApiUserRefreshTokenQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError = ErrorType<unknown>>(refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserRefreshTokenQueryKey(refreshTokenRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserRefreshToken>>> = ({ signal }) => postApiUserRefreshToken(refreshTokenRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserRefreshTokenQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserRefreshToken>>>
export type PostApiUserRefreshTokenQueryError = ErrorType<unknown>


export function usePostApiUserRefreshToken<TData = Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof postApiUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserRefreshToken<TData = Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof postApiUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserRefreshToken<TData = Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserRefreshToken<TData = Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserRefreshTokenQueryOptions(refreshTokenRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserForgetPassword = (
    forgetPasswordRequest: BodyType<ForgetPasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/forget-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgetPasswordRequest, signal
    },
      options);
    }




export const getPostApiUserForgetPasswordQueryKey = (forgetPasswordRequest?: BodyType<ForgetPasswordRequest>,) => {
    return [
    'POST', `/api/User/forget-password`, forgetPasswordRequest
    ] as const;
    }


export const getPostApiUserForgetPasswordQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError = ErrorType<unknown>>(forgetPasswordRequest: BodyType<ForgetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserForgetPasswordQueryKey(forgetPasswordRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserForgetPassword>>> = ({ signal }) => postApiUserForgetPassword(forgetPasswordRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserForgetPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserForgetPassword>>>
export type PostApiUserForgetPasswordQueryError = ErrorType<unknown>


export function usePostApiUserForgetPassword<TData = Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError = ErrorType<unknown>>(
 forgetPasswordRequest: BodyType<ForgetPasswordRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserForgetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserForgetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserForgetPassword<TData = Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError = ErrorType<unknown>>(
 forgetPasswordRequest: BodyType<ForgetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserForgetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserForgetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserForgetPassword<TData = Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError = ErrorType<unknown>>(
 forgetPasswordRequest: BodyType<ForgetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserForgetPassword<TData = Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError = ErrorType<unknown>>(
 forgetPasswordRequest: BodyType<ForgetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserForgetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserForgetPasswordQueryOptions(forgetPasswordRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserResetPassword = (
    resetPasswordRequest: BodyType<ResetPasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequest, signal
    },
      options);
    }




export const getPostApiUserResetPasswordQueryKey = (resetPasswordRequest?: BodyType<ResetPasswordRequest>,) => {
    return [
    'POST', `/api/User/reset-password`, resetPasswordRequest
    ] as const;
    }


export const getPostApiUserResetPasswordQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserResetPassword>>, TError = ErrorType<unknown>>(resetPasswordRequest: BodyType<ResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserResetPasswordQueryKey(resetPasswordRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserResetPassword>>> = ({ signal }) => postApiUserResetPassword(resetPasswordRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserResetPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserResetPassword>>>
export type PostApiUserResetPasswordQueryError = ErrorType<unknown>


export function usePostApiUserResetPassword<TData = Awaited<ReturnType<typeof postApiUserResetPassword>>, TError = ErrorType<unknown>>(
 resetPasswordRequest: BodyType<ResetPasswordRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserResetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserResetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserResetPassword<TData = Awaited<ReturnType<typeof postApiUserResetPassword>>, TError = ErrorType<unknown>>(
 resetPasswordRequest: BodyType<ResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserResetPassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserResetPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserResetPassword<TData = Awaited<ReturnType<typeof postApiUserResetPassword>>, TError = ErrorType<unknown>>(
 resetPasswordRequest: BodyType<ResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserResetPassword<TData = Awaited<ReturnType<typeof postApiUserResetPassword>>, TError = ErrorType<unknown>>(
 resetPasswordRequest: BodyType<ResetPasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserResetPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserResetPasswordQueryOptions(resetPasswordRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserChangePassword = (
    changePasswordRequest: BodyType<ChangePasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }




export const getPostApiUserChangePasswordQueryKey = (changePasswordRequest?: BodyType<ChangePasswordRequest>,) => {
    return [
    'POST', `/api/User/change-password`, changePasswordRequest
    ] as const;
    }


export const getPostApiUserChangePasswordQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserChangePassword>>, TError = ErrorType<unknown>>(changePasswordRequest: BodyType<ChangePasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserChangePasswordQueryKey(changePasswordRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserChangePassword>>> = ({ signal }) => postApiUserChangePassword(changePasswordRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserChangePasswordQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserChangePassword>>>
export type PostApiUserChangePasswordQueryError = ErrorType<unknown>


export function usePostApiUserChangePassword<TData = Awaited<ReturnType<typeof postApiUserChangePassword>>, TError = ErrorType<unknown>>(
 changePasswordRequest: BodyType<ChangePasswordRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserChangePassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserChangePassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserChangePassword<TData = Awaited<ReturnType<typeof postApiUserChangePassword>>, TError = ErrorType<unknown>>(
 changePasswordRequest: BodyType<ChangePasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserChangePassword>>,
          TError,
          Awaited<ReturnType<typeof postApiUserChangePassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserChangePassword<TData = Awaited<ReturnType<typeof postApiUserChangePassword>>, TError = ErrorType<unknown>>(
 changePasswordRequest: BodyType<ChangePasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserChangePassword<TData = Awaited<ReturnType<typeof postApiUserChangePassword>>, TError = ErrorType<unknown>>(
 changePasswordRequest: BodyType<ChangePasswordRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserChangePassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserChangePasswordQueryOptions(changePasswordRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiUserLogout = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/logout`, method: 'POST', signal
    },
      options);
    }




export const getPostApiUserLogoutQueryKey = () => {
    return [
    'POST', `/api/User/logout`
    ] as const;
    }


export const getPostApiUserLogoutQueryOptions = <TData = Awaited<ReturnType<typeof postApiUserLogout>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiUserLogoutQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiUserLogout>>> = ({ signal }) => postApiUserLogout(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiUserLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof postApiUserLogout>>>
export type PostApiUserLogoutQueryError = ErrorType<unknown>


export function usePostApiUserLogout<TData = Awaited<ReturnType<typeof postApiUserLogout>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserLogout>>,
          TError,
          Awaited<ReturnType<typeof postApiUserLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserLogout<TData = Awaited<ReturnType<typeof postApiUserLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiUserLogout>>,
          TError,
          Awaited<ReturnType<typeof postApiUserLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiUserLogout<TData = Awaited<ReturnType<typeof postApiUserLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiUserLogout<TData = Awaited<ReturnType<typeof postApiUserLogout>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiUserLogout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiUserLogoutQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiUserGetUser = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/get-user`, method: 'GET', signal
    },
      options);
    }




export const getGetApiUserGetUserMutationKey = () => ['getApiUserGetUser'] as const;

export const getGetApiUserGetUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUser>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUser>>, TError,void, TContext> => {

const mutationKey = getGetApiUserGetUserMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiUserGetUser>>, void> = () => {


          return  getApiUserGetUser(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiUserGetUserMutationResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetUser>>>

    export type GetApiUserGetUserMutationError = ErrorType<unknown>


    export const useGetApiUserGetUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUser>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiUserGetUser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiUserGetUserMutationOptions(options), queryClient);
    }
    export const getApiUserGetUserUserId = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/get-user/${userId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiUserGetUserUserIdMutationKey = () => ['getApiUserGetUserUserId'] as const;

export const getGetApiUserGetUserUserIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUserUserId>>, TError,GetApiUserGetUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUserUserId>>, TError,GetApiUserGetUserUserIdMutationVariables, TContext> => {

const mutationKey = getGetApiUserGetUserUserIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiUserGetUserUserId>>, GetApiUserGetUserUserIdMutationVariables> = (props) => {
          const {userId} = props ?? {};

          return  getApiUserGetUserUserId(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiUserGetUserUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiUserGetUserUserId>>>

    export type GetApiUserGetUserUserIdMutationError = ErrorType<unknown>
    export type GetApiUserGetUserUserIdMutationVariables = {userId: string}

    export const useGetApiUserGetUserUserId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserGetUserUserId>>, TError,GetApiUserGetUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiUserGetUserUserId>>,
        TError,
        GetApiUserGetUserUserIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiUserGetUserUserIdMutationOptions(options), queryClient);
    }
    export const getApiUserSearch = (
    params?: GetApiUserSearchParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/search`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiUserSearchMutationKey = () => ['getApiUserSearch'] as const;

export const getGetApiUserSearchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserSearch>>, TError,GetApiUserSearchMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiUserSearch>>, TError,GetApiUserSearchMutationVariables, TContext> => {

const mutationKey = getGetApiUserSearchMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiUserSearch>>, GetApiUserSearchMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiUserSearch(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiUserSearchMutationResult = NonNullable<Awaited<ReturnType<typeof getApiUserSearch>>>

    export type GetApiUserSearchMutationError = ErrorType<unknown>
    export type GetApiUserSearchMutationVariables = {params?: GetApiUserSearchParams}

    export const useGetApiUserSearch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiUserSearch>>, TError,GetApiUserSearchMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiUserSearch>>,
        TError,
        GetApiUserSearchMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiUserSearchMutationOptions(options), queryClient);
    }
    export const putApiUserUpdateUser = (
    updateUserDto: BodyType<UpdateUserDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/update-user`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto, signal
    },
      options);
    }




export const getPutApiUserUpdateUserQueryKey = (updateUserDto?: BodyType<UpdateUserDto>,) => {
    return [
    'PUT', `/api/User/update-user`, updateUserDto
    ] as const;
    }


export const getPutApiUserUpdateUserQueryOptions = <TData = Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError = ErrorType<unknown>>(updateUserDto: BodyType<UpdateUserDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPutApiUserUpdateUserQueryKey(updateUserDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiUserUpdateUser>>> = ({ signal }) => putApiUserUpdateUser(updateUserDto, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PutApiUserUpdateUserQueryResult = NonNullable<Awaited<ReturnType<typeof putApiUserUpdateUser>>>
export type PutApiUserUpdateUserQueryError = ErrorType<unknown>


export function usePutApiUserUpdateUser<TData = Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError = ErrorType<unknown>>(
 updateUserDto: BodyType<UpdateUserDto>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiUserUpdateUser>>,
          TError,
          Awaited<ReturnType<typeof putApiUserUpdateUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiUserUpdateUser<TData = Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError = ErrorType<unknown>>(
 updateUserDto: BodyType<UpdateUserDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiUserUpdateUser>>,
          TError,
          Awaited<ReturnType<typeof putApiUserUpdateUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiUserUpdateUser<TData = Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError = ErrorType<unknown>>(
 updateUserDto: BodyType<UpdateUserDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePutApiUserUpdateUser<TData = Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError = ErrorType<unknown>>(
 updateUserDto: BodyType<UpdateUserDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiUserUpdateUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutApiUserUpdateUserQueryOptions(updateUserDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiUserDeleteUser = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/User/delete-user`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiUserDeleteUserQueryKey = () => {
    return [
    'DELETE', `/api/User/delete-user`
    ] as const;
    }


export const getDeleteApiUserDeleteUserQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiUserDeleteUserQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>> = ({ signal }) => deleteApiUserDeleteUser(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiUserDeleteUserQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>>
export type DeleteApiUserDeleteUserQueryError = ErrorType<unknown>


export function useDeleteApiUserDeleteUser<TData = Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiUserDeleteUser>>,
          TError,
          Awaited<ReturnType<typeof deleteApiUserDeleteUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiUserDeleteUser<TData = Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiUserDeleteUser>>,
          TError,
          Awaited<ReturnType<typeof deleteApiUserDeleteUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiUserDeleteUser<TData = Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiUserDeleteUser<TData = Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiUserDeleteUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiUserDeleteUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiDashboardUserSignIn = (
    signIn: BodyType<SignIn>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/dashboard/User/sign-in`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signIn, signal
    },
      options);
    }




export const getPostApiDashboardUserSignInQueryKey = (signIn?: BodyType<SignIn>,) => {
    return [
    'POST', `/api/dashboard/User/sign-in`, signIn
    ] as const;
    }


export const getPostApiDashboardUserSignInQueryOptions = <TData = Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError = ErrorType<unknown>>(signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiDashboardUserSignInQueryKey(signIn);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>> = ({ signal }) => postApiDashboardUserSignIn(signIn, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiDashboardUserSignInQueryResult = NonNullable<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>>
export type PostApiDashboardUserSignInQueryError = ErrorType<unknown>


export function usePostApiDashboardUserSignIn<TData = Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiDashboardUserSignIn>>,
          TError,
          Awaited<ReturnType<typeof postApiDashboardUserSignIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiDashboardUserSignIn<TData = Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiDashboardUserSignIn>>,
          TError,
          Awaited<ReturnType<typeof postApiDashboardUserSignIn>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiDashboardUserSignIn<TData = Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiDashboardUserSignIn<TData = Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError = ErrorType<unknown>>(
 signIn: BodyType<SignIn>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserSignIn>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiDashboardUserSignInQueryOptions(signIn,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiDashboardUserRefreshToken = (
    refreshTokenRequest: BodyType<RefreshTokenRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/dashboard/User/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequest, signal
    },
      options);
    }




export const getPostApiDashboardUserRefreshTokenQueryKey = (refreshTokenRequest?: BodyType<RefreshTokenRequest>,) => {
    return [
    'POST', `/api/dashboard/User/refresh-token`, refreshTokenRequest
    ] as const;
    }


export const getPostApiDashboardUserRefreshTokenQueryOptions = <TData = Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError = ErrorType<unknown>>(refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiDashboardUserRefreshTokenQueryKey(refreshTokenRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>> = ({ signal }) => postApiDashboardUserRefreshToken(refreshTokenRequest, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiDashboardUserRefreshTokenQueryResult = NonNullable<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>>
export type PostApiDashboardUserRefreshTokenQueryError = ErrorType<unknown>


export function usePostApiDashboardUserRefreshToken<TData = Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiDashboardUserRefreshToken<TData = Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>,
          TError,
          Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiDashboardUserRefreshToken<TData = Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiDashboardUserRefreshToken<TData = Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError = ErrorType<unknown>>(
 refreshTokenRequest: BodyType<RefreshTokenRequest>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiDashboardUserRefreshToken>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiDashboardUserRefreshTokenQueryOptions(refreshTokenRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






