/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateNotificationDto,
  GetApiNotificationsInboxParams,
  GetApiNotificationsUserUserIdParams,
  GetApiNotificationsUserUserIdUnreadParams,
  NotificationPreferenceDto,
  UpdateNotificationDto
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType , BodyType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiNotifications = (
    createNotificationDto: BodyType<CreateNotificationDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNotificationDto, signal
    },
      options);
    }




export const getPostApiNotificationsQueryKey = (createNotificationDto?: BodyType<CreateNotificationDto>,) => {
    return [
    'POST', `/api/Notifications`, createNotificationDto
    ] as const;
    }


export const getPostApiNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof postApiNotifications>>, TError = ErrorType<unknown>>(createNotificationDto: BodyType<CreateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiNotificationsQueryKey(createNotificationDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiNotifications>>> = ({ signal }) => postApiNotifications(createNotificationDto, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof postApiNotifications>>>
export type PostApiNotificationsQueryError = ErrorType<unknown>


export function usePostApiNotifications<TData = Awaited<ReturnType<typeof postApiNotifications>>, TError = ErrorType<unknown>>(
 createNotificationDto: BodyType<CreateNotificationDto>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotifications>>,
          TError,
          Awaited<ReturnType<typeof postApiNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotifications<TData = Awaited<ReturnType<typeof postApiNotifications>>, TError = ErrorType<unknown>>(
 createNotificationDto: BodyType<CreateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotifications>>,
          TError,
          Awaited<ReturnType<typeof postApiNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotifications<TData = Awaited<ReturnType<typeof postApiNotifications>>, TError = ErrorType<unknown>>(
 createNotificationDto: BodyType<CreateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiNotifications<TData = Awaited<ReturnType<typeof postApiNotifications>>, TError = ErrorType<unknown>>(
 createNotificationDto: BodyType<CreateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiNotificationsQueryOptions(createNotificationDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiNotificationsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiNotificationsIdMutationKey = () => ['getApiNotificationsId'] as const;

export const getGetApiNotificationsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsId>>, TError,GetApiNotificationsIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsId>>, TError,GetApiNotificationsIdMutationVariables, TContext> => {

const mutationKey = getGetApiNotificationsIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsId>>, GetApiNotificationsIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  getApiNotificationsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsId>>>

    export type GetApiNotificationsIdMutationError = ErrorType<unknown>
    export type GetApiNotificationsIdMutationVariables = {id: string}

    export const useGetApiNotificationsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsId>>, TError,GetApiNotificationsIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsId>>,
        TError,
        GetApiNotificationsIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiNotificationsIdMutationOptions(options), queryClient);
    }
    export const putApiNotificationsId = (
    id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateNotificationDto, signal
    },
      options);
    }




export const getPutApiNotificationsIdQueryKey = (id: string,
    updateNotificationDto?: BodyType<UpdateNotificationDto>,) => {
    return [
    'PUT', `/api/Notifications/${id}`, updateNotificationDto
    ] as const;
    }


export const getPutApiNotificationsIdQueryOptions = <TData = Awaited<ReturnType<typeof putApiNotificationsId>>, TError = ErrorType<unknown>>(id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPutApiNotificationsIdQueryKey(id,updateNotificationDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiNotificationsId>>> = ({ signal }) => putApiNotificationsId(id,updateNotificationDto, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PutApiNotificationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof putApiNotificationsId>>>
export type PutApiNotificationsIdQueryError = ErrorType<unknown>


export function usePutApiNotificationsId<TData = Awaited<ReturnType<typeof putApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiNotificationsId>>,
          TError,
          Awaited<ReturnType<typeof putApiNotificationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiNotificationsId<TData = Awaited<ReturnType<typeof putApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiNotificationsId>>,
          TError,
          Awaited<ReturnType<typeof putApiNotificationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiNotificationsId<TData = Awaited<ReturnType<typeof putApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePutApiNotificationsId<TData = Awaited<ReturnType<typeof putApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string,
    updateNotificationDto: BodyType<UpdateNotificationDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutApiNotificationsIdQueryOptions(id,updateNotificationDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiNotificationsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiNotificationsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/api/Notifications/${id}`
    ] as const;
    }


export const getDeleteApiNotificationsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiNotificationsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiNotificationsId>>> = ({ signal }) => deleteApiNotificationsId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiNotificationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiNotificationsId>>>
export type DeleteApiNotificationsIdQueryError = ErrorType<unknown>


export function useDeleteApiNotificationsId<TData = Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiNotificationsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiNotificationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiNotificationsId<TData = Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiNotificationsId>>,
          TError,
          Awaited<ReturnType<typeof deleteApiNotificationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiNotificationsId<TData = Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiNotificationsId<TData = Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiNotificationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiNotificationsUserUserId = (
    userId: string,
    params?: GetApiNotificationsUserUserIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/user/${userId}`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiNotificationsUserUserIdMutationKey = () => ['getApiNotificationsUserUserId'] as const;

export const getGetApiNotificationsUserUserIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserId>>, TError,GetApiNotificationsUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserId>>, TError,GetApiNotificationsUserUserIdMutationVariables, TContext> => {

const mutationKey = getGetApiNotificationsUserUserIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsUserUserId>>, GetApiNotificationsUserUserIdMutationVariables> = (props) => {
          const {userId,params} = props ?? {};

          return  getApiNotificationsUserUserId(userId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsUserUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsUserUserId>>>

    export type GetApiNotificationsUserUserIdMutationError = ErrorType<unknown>
    export type GetApiNotificationsUserUserIdMutationVariables = {userId: string;params?: GetApiNotificationsUserUserIdParams}

    export const useGetApiNotificationsUserUserId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserId>>, TError,GetApiNotificationsUserUserIdMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsUserUserId>>,
        TError,
        GetApiNotificationsUserUserIdMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiNotificationsUserUserIdMutationOptions(options), queryClient);
    }
    export const getApiNotificationsUserUserIdUnread = (
    userId: string,
    params?: GetApiNotificationsUserUserIdUnreadParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/user/${userId}/unread`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiNotificationsUserUserIdUnreadMutationKey = () => ['getApiNotificationsUserUserIdUnread'] as const;

export const getGetApiNotificationsUserUserIdUnreadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>, TError,GetApiNotificationsUserUserIdUnreadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>, TError,GetApiNotificationsUserUserIdUnreadMutationVariables, TContext> => {

const mutationKey = getGetApiNotificationsUserUserIdUnreadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>, GetApiNotificationsUserUserIdUnreadMutationVariables> = (props) => {
          const {userId,params} = props ?? {};

          return  getApiNotificationsUserUserIdUnread(userId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsUserUserIdUnreadMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>>

    export type GetApiNotificationsUserUserIdUnreadMutationError = ErrorType<unknown>
    export type GetApiNotificationsUserUserIdUnreadMutationVariables = {userId: string;params?: GetApiNotificationsUserUserIdUnreadParams}

    export const useGetApiNotificationsUserUserIdUnread = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>, TError,GetApiNotificationsUserUserIdUnreadMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsUserUserIdUnread>>,
        TError,
        GetApiNotificationsUserUserIdUnreadMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiNotificationsUserUserIdUnreadMutationOptions(options), queryClient);
    }
    export const postApiNotificationsIdMarkRead = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/${id}/mark-read`, method: 'POST', signal
    },
      options);
    }




export const getPostApiNotificationsIdMarkReadQueryKey = (id: string,) => {
    return [
    'POST', `/api/Notifications/${id}/mark-read`
    ] as const;
    }


export const getPostApiNotificationsIdMarkReadQueryOptions = <TData = Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiNotificationsIdMarkReadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>> = ({ signal }) => postApiNotificationsIdMarkRead(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiNotificationsIdMarkReadQueryResult = NonNullable<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>>
export type PostApiNotificationsIdMarkReadQueryError = ErrorType<unknown>


export function usePostApiNotificationsIdMarkRead<TData = Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>,
          TError,
          Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotificationsIdMarkRead<TData = Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>,
          TError,
          Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotificationsIdMarkRead<TData = Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiNotificationsIdMarkRead<TData = Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsIdMarkRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiNotificationsIdMarkReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiNotificationsUserUserIdMarkAllRead = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/user/${userId}/mark-all-read`, method: 'POST', signal
    },
      options);
    }




export const getPostApiNotificationsUserUserIdMarkAllReadQueryKey = (userId: string,) => {
    return [
    'POST', `/api/Notifications/user/${userId}/mark-all-read`
    ] as const;
    }


export const getPostApiNotificationsUserUserIdMarkAllReadQueryOptions = <TData = Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostApiNotificationsUserUserIdMarkAllReadQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>> = ({ signal }) => postApiNotificationsUserUserIdMarkAllRead(userId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostApiNotificationsUserUserIdMarkAllReadQueryResult = NonNullable<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>>
export type PostApiNotificationsUserUserIdMarkAllReadQueryError = ErrorType<unknown>


export function usePostApiNotificationsUserUserIdMarkAllRead<TData = Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>,
          TError,
          Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotificationsUserUserIdMarkAllRead<TData = Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>,
          TError,
          Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostApiNotificationsUserUserIdMarkAllRead<TData = Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePostApiNotificationsUserUserIdMarkAllRead<TData = Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postApiNotificationsUserUserIdMarkAllRead>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostApiNotificationsUserUserIdMarkAllReadQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const deleteApiNotificationsUserUserIdAll = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/user/${userId}/all`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteApiNotificationsUserUserIdAllQueryKey = (userId: string,) => {
    return [
    'DELETE', `/api/Notifications/user/${userId}/all`
    ] as const;
    }


export const getDeleteApiNotificationsUserUserIdAllQueryOptions = <TData = Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteApiNotificationsUserUserIdAllQueryKey(userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>> = ({ signal }) => deleteApiNotificationsUserUserIdAll(userId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: userId !== null && userId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteApiNotificationsUserUserIdAllQueryResult = NonNullable<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>>
export type DeleteApiNotificationsUserUserIdAllQueryError = ErrorType<unknown>


export function useDeleteApiNotificationsUserUserIdAll<TData = Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>,
          TError,
          Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiNotificationsUserUserIdAll<TData = Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>,
          TError,
          Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteApiNotificationsUserUserIdAll<TData = Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDeleteApiNotificationsUserUserIdAll<TData = Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteApiNotificationsUserUserIdAll>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteApiNotificationsUserUserIdAllQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiNotificationsInbox = (
    params?: GetApiNotificationsInboxParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/inbox`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiNotificationsInboxMutationKey = () => ['getApiNotificationsInbox'] as const;

export const getGetApiNotificationsInboxMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsInbox>>, TError,GetApiNotificationsInboxMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsInbox>>, TError,GetApiNotificationsInboxMutationVariables, TContext> => {

const mutationKey = getGetApiNotificationsInboxMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsInbox>>, GetApiNotificationsInboxMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiNotificationsInbox(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsInboxMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsInbox>>>

    export type GetApiNotificationsInboxMutationError = ErrorType<unknown>
    export type GetApiNotificationsInboxMutationVariables = {params?: GetApiNotificationsInboxParams}

    export const useGetApiNotificationsInbox = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsInbox>>, TError,GetApiNotificationsInboxMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsInbox>>,
        TError,
        GetApiNotificationsInboxMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiNotificationsInboxMutationOptions(options), queryClient);
    }
    export const getApiNotificationsUnreadCount = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/unread-count`, method: 'GET', signal
    },
      options);
    }




export const getGetApiNotificationsUnreadCountMutationKey = () => ['getApiNotificationsUnreadCount'] as const;

export const getGetApiNotificationsUnreadCountMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>, TError,void, TContext> => {

const mutationKey = getGetApiNotificationsUnreadCountMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>, void> = () => {


          return  getApiNotificationsUnreadCount(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsUnreadCountMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>>

    export type GetApiNotificationsUnreadCountMutationError = ErrorType<unknown>


    export const useGetApiNotificationsUnreadCount = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsUnreadCount>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiNotificationsUnreadCountMutationOptions(options), queryClient);
    }
    export const getApiNotificationsPreferences = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/preferences`, method: 'GET', signal
    },
      options);
    }




export const getGetApiNotificationsPreferencesMutationKey = () => ['getApiNotificationsPreferences'] as const;

export const getGetApiNotificationsPreferencesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsPreferences>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsPreferences>>, TError,void, TContext> => {

const mutationKey = getGetApiNotificationsPreferencesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiNotificationsPreferences>>, void> = () => {


          return  getApiNotificationsPreferences(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiNotificationsPreferencesMutationResult = NonNullable<Awaited<ReturnType<typeof getApiNotificationsPreferences>>>

    export type GetApiNotificationsPreferencesMutationError = ErrorType<unknown>


    export const useGetApiNotificationsPreferences = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiNotificationsPreferences>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiNotificationsPreferences>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetApiNotificationsPreferencesMutationOptions(options), queryClient);
    }
    export const putApiNotificationsPreferences = (
    notificationPreferenceDto: BodyType<NotificationPreferenceDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/Notifications/preferences`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: notificationPreferenceDto, signal
    },
      options);
    }




export const getPutApiNotificationsPreferencesQueryKey = (notificationPreferenceDto?: BodyType<NotificationPreferenceDto>,) => {
    return [
    'PUT', `/api/Notifications/preferences`, notificationPreferenceDto
    ] as const;
    }


export const getPutApiNotificationsPreferencesQueryOptions = <TData = Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError = ErrorType<unknown>>(notificationPreferenceDto: BodyType<NotificationPreferenceDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPutApiNotificationsPreferencesQueryKey(notificationPreferenceDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof putApiNotificationsPreferences>>> = ({ signal }) => putApiNotificationsPreferences(notificationPreferenceDto, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PutApiNotificationsPreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof putApiNotificationsPreferences>>>
export type PutApiNotificationsPreferencesQueryError = ErrorType<unknown>


export function usePutApiNotificationsPreferences<TData = Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError = ErrorType<unknown>>(
 notificationPreferenceDto: BodyType<NotificationPreferenceDto>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiNotificationsPreferences>>,
          TError,
          Awaited<ReturnType<typeof putApiNotificationsPreferences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiNotificationsPreferences<TData = Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError = ErrorType<unknown>>(
 notificationPreferenceDto: BodyType<NotificationPreferenceDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof putApiNotificationsPreferences>>,
          TError,
          Awaited<ReturnType<typeof putApiNotificationsPreferences>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePutApiNotificationsPreferences<TData = Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError = ErrorType<unknown>>(
 notificationPreferenceDto: BodyType<NotificationPreferenceDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePutApiNotificationsPreferences<TData = Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError = ErrorType<unknown>>(
 notificationPreferenceDto: BodyType<NotificationPreferenceDto>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof putApiNotificationsPreferences>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPutApiNotificationsPreferencesQueryOptions(notificationPreferenceDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






