/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Social API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GetApiAdminAuditLogsParams
} from '../../models';

import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getApiAdminAuditLogs = (
    params?: GetApiAdminAuditLogsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/admin/audit-logs`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiAdminAuditLogsMutationKey = () => ['getApiAdminAuditLogs'] as const;

export const getGetApiAdminAuditLogsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAuditLogs>>, TError,GetApiAdminAuditLogsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAuditLogs>>, TError,GetApiAdminAuditLogsMutationVariables, TContext> => {

const mutationKey = getGetApiAdminAuditLogsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApiAdminAuditLogs>>, GetApiAdminAuditLogsMutationVariables> = (props) => {
          const {params} = props ?? {};

          return  getApiAdminAuditLogs(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApiAdminAuditLogsMutationResult = NonNullable<Awaited<ReturnType<typeof getApiAdminAuditLogs>>>

    export type GetApiAdminAuditLogsMutationError = ErrorType<unknown>
    export type GetApiAdminAuditLogsMutationVariables = {params?: GetApiAdminAuditLogsParams}

    export const useGetApiAdminAuditLogs = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApiAdminAuditLogs>>, TError,GetApiAdminAuditLogsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getApiAdminAuditLogs>>,
        TError,
        GetApiAdminAuditLogsMutationVariables,
        TContext
      > => {
      return useMutation(getGetApiAdminAuditLogsMutationOptions(options), queryClient);
    }
